### ISSUE TITLE
Login callback gets registered twice

### ISSUE THREAD

**Issue by Nopik** [underscopeio/react-native-facebook-account-kit#10]
During first login loginWithPhone() works fine, but if I logout and call loginWithPhone() again, I'm receiving red screen complaining about login callback being already registered.

**Comment by Nopik** [comment]
I've upgraded to 0.1.0, rebuilt everything and this problem doesnt happening anymore. Not sure what it was, as there were apparently no fixes for this between 0.0.5 and 0.1.0. Closing for now, if I will ever see that problem again, I'll reopen.

**Comment by gaguirre** [comment]
Nice! Let me know if it happens again 👍

**Comment by Nopik** [comment]
This actually still exists. Way to reproduction:
- start sample ios app from this repo
- enter `12` as phone number (for US)
- press `Next`
- press `Cancel`
Red screen shows up.

Moreover, in such situation `logout()` returns promise which never gets resolved nor rejected.

**Comment by gaguirre** [comment]
Good to have repro steps! I'll debug it.

**Comment by gaguirre** [comment]
It's fixed in recently published version **0.4.0**

**Comment by Nopik** [comment]
Thanks, it seems to work.
