### ISSUE TITLE
Open App link ak{appid}://authorize doesn't open the app in Android

### ISSUE THREAD

**Issue by mypark** [underscopeio/react-native-facebook-account-kit#100]
### Issue Description

Open App link ak{appid}://authorize doesn't open the app

### Steps to Reproduce / Code Snippets

login using email, click on email link, click the "open the app" button

#### Expected Results

To open the app

### Additional Information

* React Native Account Kit version: 0.7.0
* React Native version: 0.41.2
* Platform(s) (iOS, Android, or both?): Android

**Comment by mypark** [comment]
So I found the answer in two places, initially I saw that you needed to update your AndroidManifest.xml by adding an intent to the account activity - as noted in the `Addtional Email Features` section of the documentation https://developers.facebook.com/docs/accountkit/android/configuration/

      <activity android:name="com.facebook.accountkit.ui.AccountKitActivity">
          <intent-filter>
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              <data android:scheme="@string/ak_login_protocol_scheme" />
          </intent-filter>
      </activity>

However, this does not work correctly as it can land you on the wrong step in the account kit activity flow.  I looked at their sample android project and saw that the intent should be with the `AccountKitEmailRedirectActivity`, at which point it started working correctly.

      <activity android:name="com.facebook.accountkit.ui.AccountKitEmailRedirectActivity">
          <intent-filter>
              <action android:name="android.intent.action.VIEW" />
              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />
              <data android:scheme="@string/ak_login_protocol_scheme" />
          </intent-filter>
      </activity>

**Comment by danhnguyeen** [comment]
It didn't work for me anymore.
Could you help me please?
