### ISSUE TITLE
Cannot link library on RN 0.40

### ISSUE THREAD

**Issue by nmhcoc** [underscopeio/react-native-facebook-account-kit#101]
### Issue Description
I cannot link this library in ios.
![screen shot 2017-10-04 at 3 59 33 pm](https://user-images.githubusercontent.com/24821452/31167794-789344fa-a91d-11e7-96b3-227b6eb1dabb.png)
How can i fix it?
Thank.

* React Native Account Kit version: 0.9.0
* React Native version: 0.40
* Platform(s) (iOS, Android, or both?): ios
* xCode version: 9

**Comment by gaguirre** [comment]
@nmhcoc if your RN version is 0.40 then you should use a previous version of this module (I think is ^0.7.0 version)
