### ISSUE TITLE
Can I disable initialPhoneNumber?

### ISSUE THREAD

**Issue by xuho** [underscopeio/react-native-facebook-account-kit#102]
When I', not add initialPhoneNumber property in RNAccountKit.configure() method, it give me number like this:
![image](https://user-images.githubusercontent.com/13913140/31644347-fea799fe-b31f-11e7-9618-834254095458.png)
Or when I put: initialPhoneNumber: '', I got same issue?
How can I fix it?
Thank.

**Comment by kdastan** [comment]
@xuho did you solve issue ? I think this number is just your Android Emulator's number and it shouldn't be on real device.
