### ISSUE TITLE
Framework not found AccountKit for architecture x86_64

### ISSUE THREAD

**Issue by hai2014bk** [underscopeio/react-native-facebook-account-kit#103]
Hi guys, thanks for amazing library, but i'm facing this, with nothing in my mind that this problem come from

It happened on iOS, when i build my app, i followed all the installation and configuration guide, but face the same. 

![screen shot 2017-10-18 at 12 08 59 pm](https://user-images.githubusercontent.com/16575101/31701830-2a16a3f4-b3fd-11e7-8d85-868cbe84df54.png)

So anyone can help me, is's urgent :(

**Comment by gaguirre** [comment]
Hi @hai2014bk, they are just warnings because you're targeting an old iOS version (8.0) which is not compatible with the one the library was built for (9.2).
However this is not why the build is failing. Take a deeper look to the logs to see what is really causing the linker to fail and post it here.

**Comment by afilp** [comment]
Hi @gaguirre, could this be a similar problem with the following Android one that I am facing? (I cannot compile)

https://github.com/underscopeio/react-native-facebook-account-kit/issues/107

**Comment by Compa259** [comment]
@hai2014bk : Did u solved this problem yet. Because I am also in trouble like this. Thanks for any help!...

**Comment by afilp** [comment]
@Compa259 Do you also have the problem I am having in Android? I ask because this may be related to some overall versioning problem. This is my similar (I think) issue in Android: #107

**Comment by afilp** [comment]
@hai2014bk @Compa259 I have the same problem.

**Comment by congvd** [comment]
Hi guys, I solved this problem.
Steps :
First, link the AccountKit SDK to your project following these steps: 
> Open with XCode your project
> Open with Finder the node_modules/react-native-facebook-account-kit/ios folder
> move AccountKit.framework and AccountKitStrings.bundle to another folder
> Drag and drop AccountKit.framework and AccountKitStrings.bundle from Finder to your project in XCode (IMPORTANT: select the "Copy items if needed" option)

**Comment by phumaster** [comment]
I find the solution and work well:

Copy `AccountKit.framework` and `AccountKitStrings.bundle` to your project in `ios` folder (Ex: `your_react_native_project/ios/COPY_TO_HERE`)
Then, in your project in xcode. Right click -> add file to "your project" and select `AccountKit.framework` and `AccountKitStrings.bundle` select the "Copy items if needed" option.
Clean project and rebuild.
Good luck!

**Comment by kdastan** [comment]
It didn't work for me, because **react-native link** didn't add framework properly. To fix this, I had to add AccountKit.framework and AccountKitStrings.bundle by myself. Select in 'Targets' your app name, then find 'Link Binary with Libraries' in 'Build Phases' and add those 2 files by clicking plus sign. It should help you.

**Comment by anastely** [comment]
@phumaster  
I got this error, 

Showing Recent Messages
:-1: Multiple commands produce '/Users/anas/Library/Developer/Xcode/DerivedData/mstore-fpvndgippwancegertlwurjoosod/Build/Products/Debug-iphonesimulator/mstore.app/AccountKitStrings.bundle':
1) Target 'mstore' (project 'mstore') has copy command from '/Users/anas/Desktop/App/codecanyon-17010642-beostore-complete-react-native-template-for-ecommerce/mstore-3.9.1/mstore-pro/ios/AccountKitStrings.bundle' to '/Users/anas/Library/Developer/Xcode/DerivedData/mstore-fpvndgippwancegertlwurjoosod/Build/Products/Debug-iphonesimulator/mstore.app/AccountKitStrings.bundle'
2) Target 'mstore' (project 'mstore') has copy command from '/Users/anas/Desktop/App/codecanyon-17010642-beostore-complete-react-native-template-for-ecommerce/mstore-3.9.1/mstore-pro/scripts/FacebookSDK/AccountKitStrings.bundle' to '/Users/anas/Library/Developer/Xcode/DerivedData/mstore-fpvndgippwancegertlwurjoosod/Build/Products/Debug-iphonesimulator/mstore.app/AccountKitStrings.bundle'

**Comment by 0x6675** [comment]
@anastely what is your react-native version? I think the version is higher than me. Then you got that error.
