### ISSUE TITLE
How do I change default language?

### ISSUE THREAD

**Issue by tuan072090** [underscopeio/react-native-facebook-account-kit#105]
Anyone know how to change the default language (English) to another language?

**Comment by chileung69** [comment]
In iOS, you can add a support language in XCode project. In Android, there should support multi-language default.

**Comment by hoanglinh2k7** [comment]
In android 8, I can't change language default of facebook account kit layout. Anyone know how to change it?

**Comment by gaguirre** [comment]
@tuan072090 @imcodervn I'm afraid the Account Kit SDK will use the device's language settings and you can't change that behavior.
