### ISSUE TITLE
Rejected app while logging app connected to an IPv6 network.

### ISSUE THREAD

**Issue by Toriki07** [underscopeio/react-native-facebook-account-kit#106]
App Store tested IPv6 compatibility and rejected app as it crashes while logging in with FB accountkit sms.

Are there any additional work to implement IPv6 compatibility in my app?

* React Native Account Kit version: [0.6.2]
* React Native version: [0.45.1]
* Platform(s) (iOS]

**Comment by cmendes0101** [comment]
Every we get rejected about IPv6 it was always really about logging in by phone number. This has happened like 4+ times.

They do not use their own phone numbers so they keep rejecting at that point from my past experience. We had to setup a number on Twilio and a receiving SMS page so they can enter a specific test number and get the code to login.

**Comment by jpgarcia** [comment]
Closing this due inactivity. Fell free to reopen it if still facing the issue
