### ISSUE TITLE
error: package io.underscope.react.fbak does not exist

### ISSUE THREAD

**Issue by afilp** [underscopeio/react-native-facebook-account-kit#107]
Hello,

unfortunately, I get this error in Android, with latest versions:

```
\MainApplication.java:6: error: package io.underscope.react.fbak does not exist
import io.underscope.react.fbak.RNAccountKitPackage;
                               ^
E:\testMobileApp\android\app\src\main\java\com\testmobileapp\MainApplication.java:42: error: cannot find symbol
          new RNAccountKitPackage(),
              ^
  symbol: class RNAccountKitPackage
2 errors
:app:compileDebugJavaWithJavac FAILED
```

The `MainApplication.java` seems OK (or not?):

```
...
import com.facebook.react.ReactApplication;
import io.underscope.react.fbak.RNAccountKitPackage;
...
```

```
...
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new RNAccountKitPackage(),
...
```

### Additional Information

* React Native Account Kit version: 0.9.0
* React Native version: 0.49.5
* Platform(s) (iOS, Android, or both?): Android

**Comment by gaguirre** [comment]
Apparently the library was not linked properly.
Try again and use git to see the diff when doing it: you should see changes on `build.gradle`, `settings.gradle` and `MainApplication.java`.

**Comment by jpgarcia** [comment]
@afilp as @gaguirre mentioned check your `settings.gradle` it seems you're missing this:

```java
include ':react-native-facebook-account-kit'
project(':react-native-facebook-account-kit').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-facebook-account-kit/android')
```
I'm closing this issue, feel free to re-open it if it doesn't work

**Comment by putin111** [comment]
do you help me fix this error?

**Comment by gaguirre** [comment]
@putin111 have you tried the solution suggested by @jpgarcia above?

**Comment by ppv94** [comment]
@gaguirre The same issue for me also
there is no problem in settings.gradle, library was linked properly.
MainApplication.java:7: error: package io.underscope.react.fbak does
not exist
import io.underscope.react.fbak.RNAccountKitPackage;
                               ^
MainApplication.java:68: error: cannot find symbol
            new RNAccountKitPackage(),
