### ISSUE TITLE
Style issue for the phone login

### ISSUE THREAD

**Issue by wenweicui** [underscopeio/react-native-facebook-account-kit#109]
### Issue Description

For the phone number login page, the instruction text has less vertical padding space compare to the screenshot provided on https://developers.facebook.com/docs/accountkit/ios/customizing. Please help me find the issue. Thanks!
<img width="258" alt="screen shot 2017-12-05 at 12 21 57 pm" src="https://user-images.githubusercontent.com/11566077/33621431-bc5468b0-d9b8-11e7-9886-35d9da43ef69.png">
<img width="599" alt="screen shot 2017-12-05 at 12 24 52 pm" src="https://user-images.githubusercontent.com/11566077/33621432-bedeab5e-d9b8-11e7-9795-5b76db4d2c57.png">

### Steps to Reproduce / Code Snippets

Should be the same code as the examples 
```js
RNAccountKit.configure({
      theme: {
        // Background
        //backgroundColor: Color.rgba(0,0,0,0.4),
        backgroundColor: Color.rgba(0,0,0,0.4),
        backgroundImage: 'backgroundAK.png',
        // Button
        buttonBackgroundColor: Color.hex('#6BB9F0'),
        buttonBorderColor: Color.hex('#6BB9F0'),
        buttonTextColor: Color.hex('#fff'),
        // Button disabled
        buttonDisabledBackgroundColor: Color.hex('#eee'),
        buttonDisabledBorderColor: Color.hex(F8Colors.cellBorder),
        buttonDisabledTextColor: Color.hex('#ccc'),
        // Header
        headerBackgroundColor: Color.hex('#fff'),
        headerButtonTextColor: Color.hex('#000'),
        headerTextColor: Color.hex('#000'),
        // Input
        inputBackgroundColor: Color.rgba(255, 255, 255, 0.8),
        inputBorderColor: Color.hex('#ccc'),
        inputTextColor: Color.hex('#000'),
        // Others
        iconColor: Color.hex(F8Colors.icon),
        textColor: Color.hex('#fff'),
        titleColor: Color.hex('#fff'),
        // Header
        statusBarStyle: StatusBarStyle.LightContent, // or StatusBarStyle.Default
      },
      responseType: 'code', // 'token'|'code' , 'token' by default,
      titleType: 'login',
      initialAuthState: '',
      //initialEmail: 'some.initial@email.com',
      initialPhoneCountryPrefix: '+1',
      //initialPhoneNumber: '123-456-7890',
      facebookNotificationsEnabled: true, // true|false, true by default
      readPhoneStateEnabled: true, // true|false, true by default,
      receiveSMS: true, // true|false, true by default,
      //countryWhitelist: ['AR'], // [] by default
      //countryBlacklist: ['US'], // [] by default
      defaultCountry: 'CA'
    })
```

#### Expected Results

Expecting more vertical padding space between the phone input box and Next button
<img width="599" alt="screen shot 2017-12-05 at 12 24 52 pm" src="https://user-images.githubusercontent.com/11566077/33620944-5737d260-d9b7-11e7-8cc3-f33ccfb078a7.png">

### Additional Information

* React Native Account Kit version: v0.9.0
* React Native version: v0.50.4
* Platform(s) (iOS, Android, or both?): iOS Platforms

**Comment by gaguirre** [comment]
I think thats related to the native AccountKit SDK itself.
You could post the issue in Facebook developer bugs (see an example [here](https://developers.facebook.com/bugs/926401704138172/) )
