### ISSUE TITLE
Compile Error in Android, ReactNativeContacts is not abstract and does not override abstract method createJSModules() in ReactPackage 

### ISSUE THREAD

**Issue by chileung69** [underscopeio/react-native-facebook-account-kit#111]
When I compile and get error on override function
ReactNativeContacts is not abstract and does not override abstract method createJSModules() in ReactPackage 

I solved by add a override function in library.
@Override
public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
}

Can solve in next version? Thank you.

**Comment by jpgarcia** [comment]
Could you try with the latest version? I'm closing this one. Feel free to reopen it if still happening
