### ISSUE TITLE
[Style] Change button color when pressed ?

### ISSUE THREAD

**Issue by RoshOne4** [underscopeio/react-native-facebook-account-kit#115]
Hello,

Is this possible to change the color of the button when pressed ?

Thanks.

![img-0301](https://user-images.githubusercontent.com/26284106/35757460-612fa1b2-086f-11e8-866a-92d2ac2c88ac.PNG)

**Comment by jpgarcia** [comment]
Nope, facebook sdk doesn't allow that. You can only set the enabled/disabled states stye 😢
