### ISSUE TITLE
Debug Flag

### ISSUE THREAD

**Issue by zachrnolan** [underscopeio/react-native-facebook-account-kit#118]
Facebook references a debug flag in their Account Kit FAQ (https://developers.facebook.com/docs/accountkit/faq)

When you click on the link it takes you to the web documentation. Is there any type of debug flag we can set for iOS and Android? Their documentation is unclear on this.

**Comment by jpgarcia** [comment]
It seems that the flag is only for the web. I couldn't find any reference of that flag for Android nor IOS.
