### ISSUE TITLE
v 0.1.0 configDefaults needs defaultCountry

### ISSUE THREAD

**Issue by fabriziomoscon** [underscopeio/react-native-facebook-account-kit#12]
Testing on Android I got an error red screen saying something like "impossible to find ... defaultCountry" in RNAccountKitModule.jave:240"

Should it be added here?
https://github.com/underscopeio/react-native-facebook-account-kit/blob/master/index.js#L16-L24

Or is it a necessary user specific configuration after `0.1.0`? Because before that was not the case, since my code was using the module without the need to any custom configuration.
Thanks for the clarification

**Comment by gaguirre** [comment]
Thanks @fabriziomoscon for reporting this issue.
Should be fixed in version **0.1.1**

**Comment by fabriziomoscon** [comment]
Great!
