### ISSUE TITLE
How could I remove this back button out of the login screen

### ISSUE THREAD

**Issue by Zacele** [underscopeio/react-native-facebook-account-kit#124]
How could I remove this "Back" button out of the login screen. Thank you very much.

<img width="387" alt="screenshot 2018-04-06 10 56 51" src="https://user-images.githubusercontent.com/25264866/38402809-3d3babf2-3989-11e8-973f-02f2ba52f950.png">

**Comment by ismailhamadi** [comment]
@Zacele did you find a solution for that, if so please share it with us if you can.
Thanks.

**Comment by Zacele** [comment]
@ismailhamadi actually I just know how to get rid of it on Android. I'm using React-Navigation so by setting the header to null. I'm able to disable the header. Doesn't have any effect on iOS though.

**Comment by ismailhamadi** [comment]
Thanks @Zacele for the information.

**Comment by jpgarcia** [comment]
Apparently there's no way to do that. Closing this one
