### ISSUE TITLE
Read sms automatically

### ISSUE THREAD

**Issue by rassemdev** [underscopeio/react-native-facebook-account-kit#126]
Is there any way to read the verification message automatically, instead of typing it?

**Comment by psanowski** [comment]
Any idea why iOS 12 Security code AutoFill not working with FAK?

**Comment by jpgarcia** [comment]
Hi @psanowski as described by Facebook in their [FAQ page](https://developers.facebook.com/docs/accountkit/faq) the feature is not supported by the IOS SDK yet. 

<img width="780" alt="screen shot 2018-10-08 at 6 38 32 pm" src="https://user-images.githubusercontent.com/95109/46635058-7dd4dd00-cb29-11e8-9683-3ba3419e87a4.png">

It seems that they have not implemented  the [oneTimeCode](https://developer.apple.com/documentation/uikit/uitextcontenttypeonetimecode?language=objc) feature you mention. 

You can submit the issue on the [SDK repo](https://github.com/facebook/facebook-objc-sdk). Maybe @codytwinton has some news about it

**Comment by rassemdev** [comment]
@psanowski I read a article about that. It is security issue. Thats why iphone is not allowing auto read sms.

**Comment by psanowski** [comment]
Update, one time code autofill works when I have iPhone languge set to English
and not working with Polish language
![img_0908](https://user-images.githubusercontent.com/33316862/46657581-e2874a80-cbb0-11e8-95f3-fc5d5d5cd979.jpeg)
![img_0909](https://user-images.githubusercontent.com/33316862/46657594-e87d2b80-cbb0-11e8-9afa-9d2a0f03fad5.jpeg)

**Comment by psanowski** [comment]
I submitted the issue to the SDK
https://developers.facebook.com/support/bugs/530034470754541/

**Comment by jpgarcia** [comment]
@psanowski So it worked OOTB then 👍 

I guess Polish is not working as they detect certain words in the message. 

I found the following phrase in this [article](https://www.benthamsgaze.org/2018/06/08/security-code-autofill-is-this-new-ios-feature-a-security-risk-for-online-banking/) which also describes what @rassemdev mentioned:

> The code is detected in a message based on heuristics such as proximity to the words ‘code’ or ‘passcode’, which are used in messages delivering 2FA codes and TANs alike

@rassemdev could you get the auto detect feature working on Android? If not I can spend some time trying to get it working...

**Comment by rassemdev** [comment]
@jpgarcia i haven't tried to implement it after that. Currently im working on another project. So not getting enough time to implement that.It will be nice, you if try it out.

**Comment by jose2007kj** [comment]
i shall try to implement autodetect otp in android..... if successful i will post my update  @jpgarcia

**Comment by jose2007kj** [comment]
updated readme for adding permission for reading sms automatically and created pull request https://github.com/underscopeio/react-native-facebook-account-kit/pull/160

**Comment by shubhamverma27** [comment]
How to do this on IOS (React Native)?
Any tutorial?

**Comment by hpsurekha** [comment]
I am using the '@twotalltotems/react-native-otp-input' library for auto-detect but it seems it not detecting, so does anyone have an idea how to integrate it into ios to detect OTP from SMS, and is there any format to autodetect or any other library which work best in android and ios.

Any type of help is appreciated.
