### ISSUE TITLE
How to get the phone number that typed

### ISSUE THREAD

**Issue by rassemdev** [underscopeio/react-native-facebook-account-kit#128]
Is there any way to get the phone number that we typed for verification?

**Comment by Chatharaju** [comment]
+1
I would like to know it as well.

**Comment by kishanverma26** [comment]
> getCurrentAccount will give you that.
> 
> RNAccountKit.getCurrentAccount()
> .then((account) => {
> console.log(`Current account: ${account}`)
> })

Not working for me
