### ISSUE TITLE
Make OTP submit button press automated

### ISSUE THREAD

**Issue by swadhin-** [underscopeio/react-native-facebook-account-kit#129]
### Issue Description

After OTP is auto-filled in user needs to press submit button. Should be a way to auto submit the OTP.

### Steps to Reproduce / Code Snippets

- Provide phone number
- Wait till otp fills in
- Observe that user needs to press submit button to complete the process

#### Expected Results

Should auto login after otp fills in

### Additional Information

* React Native Account Kit version: latest
* React Native version: 0.48.10
* Platform(s) (iOS, Android, or both?): Android

**Comment by gaguirre** [comment]
Hi @swadhin-, the auto-fill is handled by the AccountKit SDK.
AFAIK that _auto login_ feature is not an option, but it's always up to Facebook and the AccountKit developers.

**Comment by jpgarcia** [comment]
There's no way to do that, Facebook SDK doesn't allow that.
