### ISSUE TITLE
iOS app is crashing in production

### ISSUE THREAD

**Issue by thejasreem** [underscopeio/react-native-facebook-account-kit#133]
Hi,
Can anyone help me out with this issue?
The issue with account kit RCT native module.

![screen shot 2018-05-15 at 11 44 02 am](https://user-images.githubusercontent.com/19645979/40039773-57eb174c-5835-11e8-9da5-5749b6e48f7c.png)

* React Native Account Kit version: 0.9.0
* React Native version: 0.51
* Platform(s) (iOS, Android, or both?): iOS

**Comment by aschenkel** [comment]
possible duplicate of https://github.com/underscopeio/react-native-facebook-account-kit/issues/120 ?
Is this also happening on iOS11?

**Comment by gaguirre** [comment]
Hi @thejasreem, we need more info to see why this is happening.
I'm closing this but feel free to reopen it with the repro steps.
