### ISSUE TITLE
react-native-firebase and react-native-facebook-account-kit

### ISSUE THREAD

**Issue by saveliy-kremen** [underscopeio/react-native-facebook-account-kit#136]
### Issue Description

Connecting react-native-firebase results in a bug in the react-native-facebook-account-kit. Using the keyboard in the react-native-facebook-account-kit crashes the application

### Additional Information

* React Native Account Kit version: 0.9.3
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): Android

**Comment by hmaamoun** [comment]
Is there any update or fix here? Any workarounds?

**Comment by iVahan** [comment]
I have same issue . 
Didn’t find class “android.support.v4.view.KeyEventCompat”

Please give some updates 
Thank you

**Comment by aschenkel** [comment]
Hey @saveliy-kremen !  What Firebase version are you using?

We have a working application which is using the latest firebase version (but is on RN051) and doesn't have this issue

```
    "react-native": "0.51.0",
    "react-native-facebook-account-kit": "0.9.3",
    "react-native-firebase": "4.2.0",
```

Is this happening on every device?

**Comment by gaguirre** [comment]
Closing this, please reopen if the issue still persist.

**Comment by bijoycse** [comment]
I have same issues.. apps is crash
 "react-native-facebook-account-kit": "^1.0.2",
 "react-native-firebase": "^5.1.0",

**Comment by tmjordan** [comment]
there is a conflict with google play services. React native firebase and account kit use different play services.

**Comment by bijoycse** [comment]
_I have solved it by simply down grade the version of react-native-facebook-account-kit as well as add implementation "com.android.support:design:27.1.0"_
------------------------------------------------------------------------------
before : "react-native-facebook-account-kit": "^1.0.2"

now : "react-native": "0.57.8",
          "react-native-facebook-account-kit": "^0.11.0",
          "react-native-firebase": "^5.1.0"

**its working now along with triangle integration 1. react-native-maps 2. react-native-fire-base 3. react-native-facebook-account-kit**

**Comment by phanbien9x** [comment]
I use react native fcm. Have the same error. 
"react-native": "0.58.5",
"react-native-facebook-account-kit": "^1.1.0",
"react-native-fcm": "^16.2.4",

**Comment by bijoycse** [comment]
Better to make it two individual part.
1. Part 1 Integrate 
"react-native": "0.58.5",
"react-native-facebook-account-kit": "^1.1.0"
*Observe its work or not*
2. Part 2 Integrate 
"react-native": "0.58.5",
"react-native-fcm": "^16.2.4",
_last combine it_

**Comment by jpgarcia** [comment]
Guys take a look at my comments here => https://github.com/underscopeio/react-native-facebook-account-kit/issues/157#issuecomment-423949726
