### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by nzhtrtlc** [underscopeio/react-native-facebook-account-kit#146]
### Issue Description
Hello, this package works fine on IOS with the versions notes below.
But in android it could not build successful.
<details>
    <summary>Build fail log</summary>

> JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareAndroidArchLifecycleRuntime100Library
:app:prepareComAndroidSupportAnimatedVectorDrawable2610Library
:app:prepareComAndroidSupportAppcompatV72610Library
:app:prepareComAndroidSupportDesign2421Library
:app:prepareComAndroidSupportRecyclerviewV72421Library
:app:prepareComAndroidSupportSupportCompat2610Library
:app:prepareComAndroidSupportSupportCoreUi2610Library
:app:prepareComAndroidSupportSupportCoreUtils2610Library
:app:prepareComAndroidSupportSupportFragment2610Library
:app:prepareComAndroidSupportSupportMediaCompat2610Library
:app:prepareComAndroidSupportSupportV42610Library
:app:prepareComAndroidSupportSupportVectorDrawable2610Library
:app:prepareComFacebookAndroidAccountKitSdk4230Library
:app:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library
:app:prepareComFacebookFrescoDrawee190Library
:app:prepareComFacebookFrescoFbcore190Library
:app:prepareComFacebookFrescoFresco190Library
:app:prepareComFacebookFrescoImagepipeline190Library
:app:prepareComFacebookFrescoImagepipelineBase190Library:app:prepareComFacebookFrescoImagepipelineOkhttp3190Library:app:prepareComFacebookReactReactNative0560Library
:app:prepareComFacebookSoloaderSoloader030Library
:app:prepareOrgWebkitAndroidJscR174650Library
:react-native-facebook-account-kit:preBuild UP-TO-DATE
:react-native-facebook-account-kit:preReleaseBuild UP-TO-DATE
:react-native-facebook-account-kit:checkReleaseManifest
:react-native-facebook-account-kit:preDebugAndroidTestBuild UP-TO-DATE
:react-native-facebook-account-kit:preDebugBuild UP-TO-DATE
:react-native-facebook-account-kit:preDebugUnitTestBuild UP-TO-DATE
:react-native-facebook-account-kit:preReleaseUnitTestBuild UP-TO-DATE
:react-native-facebook-account-kit:prepareAndroidArchLifecycleRuntime100Library
:react-native-facebook-account-kit:prepareComAndroidSupportAnimatedVectorDrawable2610Library
:react-native-facebook-account-kit:prepareComAndroidSupportAppcompatV72610Library
:react-native-facebook-account-kit:prepareComAndroidSupportDesign2421Library
:react-native-facebook-account-kit:prepareComAndroidSupportRecyclerviewV72421Library
:react-native-facebook-account-kit:prepareComAndroidSupportSupportCompat2610Library
:react-native-facebook-account-kit:prepareComAndroidSupportSupportCoreUi2610Library
:react-native-facebook-account-kit:prepareComAndroidSupportSupportCoreUtils2610Library
:react-native-facebook-account-kit:prepareComAndroidSupportSupportFragment2610Library
:react-native-facebook-account-kit:prepareComAndroidSupportSupportMediaCompat2610Library
:react-native-facebook-account-kit:prepareComAndroidSupportSupportV42610Library
:react-native-facebook-account-kit:prepareComAndroidSupportSupportVectorDrawable2610Library
:react-native-facebook-account-kit:prepareComFacebookAndroidAccountKitSdk4230Library
:react-native-facebook-account-kit:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library
:react-native-facebook-account-kit:prepareComFacebookFrescoDrawee190Library
:react-native-facebook-account-kit:prepareComFacebookFrescoFbcore190Library
:react-native-facebook-account-kit:prepareComFacebookFrescoFresco190Library
:react-native-facebook-account-kit:prepareComFacebookFrescoImagepipeline190Library
:react-native-facebook-account-kit:prepareComFacebookFrescoImagepipelineBase190Library
:react-native-facebook-account-kit:prepareComFacebookFrescoImagepipelineOkhttp3190Library
:react-native-facebook-account-kit:prepareComFacebookReactReactNative0560Library
:react-native-facebook-account-kit:prepareComFacebookSoloaderSoloader030Library
:react-native-facebook-account-kit:prepareOrgWebkitAndroidJscR174650Library
:react-native-facebook-account-kit:prepareReleaseDependencies
:react-native-facebook-account-kit:compileReleaseAidl
:react-native-facebook-account-kit:compileReleaseNdk NO-SOURCE
:react-native-facebook-account-kit:compileLint
:react-native-facebook-account-kit:copyReleaseLint NO-SOURCE
:react-native-facebook-account-kit:compileReleaseRenderscript
:react-native-facebook-account-kit:generateReleaseBuildConfig
:react-native-facebook-account-kit:generateReleaseResValues
:react-native-facebook-account-kit:generateReleaseResources
:react-native-facebook-account-kit:mergeReleaseResources
:react-native-facebook-account-kit:processReleaseManifest
:react-native-facebook-account-kit:processReleaseResources
/Users/Nezih/Documents/projects/react-native/FoxtailApp/node_modules/react-native-facebook-account-kit/android/build/intermediates/res/merged/release/values-v26/
values-v26.xml:15:21-54: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
/Users/Nezih/Documents/projects/react-native/FoxtailApp/node_modules/react-native-facebook-account-kit/android/build/intermediates/res/merged/release/values-v26/
  values-v26.xml:15: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
  :react-native-facebook-account-kit:processReleaseResources FAILED
  FAILURE: Build failed with an exception.
  * What went wrong:
  Execution failed for task ':react-native-facebook-account-kit:processReleaseResources'.
  > com.android.ide.common.process.ProcessException: Failed to execute aapt
  * Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
  BUILD FAILED
  Total time: 6.589 secs
</details>

### Steps to Reproduce / Code Snippets
react-native run-android

#### Expected Results

*** BUILD SUCCESFULLED **

### Additional Information

* React Native Account Kit version: ^0.10.1
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): Both

BTW, i followed the docs for android i edited strings.xml and manifes file also i checked java package if it is registered. Everything is okay but still can not build successful.
Help please.

**Comment by nzhtrtlc** [comment]
I removed android:keyboardNavigationCluster attribute from source code of this plugin. 
Then its works.
Now the question is: when i type npm install again this plugin will be turn back to default codes. So my override will be gone. How can i keep my changes and get updates from this plugin too ?

**Comment by nzhtrtlc** [comment]
@gaguirre Actually i was my bad. I looked into build directory, if you really curious here is the path:

node_modules/react-native-facebook-account-kit/android/build/intermediates/res/merged/release/values-v26/values-v26.xml

This is wrong place to change because this file is under build directory.
So, i removed node_modules and re-installed packages. Then i tried to run android but it failed again. This time i did receive error about allowBackup
path: node_modules/react-native-facebook-account-kit/android/src/main/AndroidManifest.xml
I removed the attribute which includes allowBackup then re-run the app and its works.
Of course when i do npm install again my change will be gone i think. But now, i know how to fix the problem.

**Comment by dantn93** [comment]
@nzhtrtlc please make a guideline to fix it. Thanks.

**Comment by dantn93** [comment]
@nzhtrtlc Do you just remove allowBackup attribute? I did but it still fails.
Please make a guideline to fix it. Thanks

**Comment by KeegsMcGeegs** [comment]
I'm still having this same issue. Has anybody found a solution yet? @nzhtrtlc I tried removing the android:keyboardNavigationCluster attribute from node_modules/react-native-facebook-account-kit/android/build/intermediates/res/merged/release/values-v26/values-v26.xml but it seems to come back everytime I run the android build. Removing allowBackup didn't work either

**Comment by nzhtrtlc** [comment]
Hi @dantn93 and @KeegsMcGeegs 
What is your OS ?
@dantn93 What did  you receive that time ?
I will try it on my windows environment too, i let you know if i get any error and its solution

**Comment by KeegsMcGeegs** [comment]
@nzhtrtlc  Windows 10

**Comment by jpgarcia** [comment]
Hi guys, I just filled out a new issue regarding the `allowBackup` error and I will summit the fix soon.

Regarding the `android:keyboardNavigationCluster` error I could workaround it by doing the following steps (with a **RN 0.56.0** sample): 

1. Update `gradle` dependency in the `android/build.gradle` file to:

```xml
classpath 'com.android.tools.build:gradle:3.0.1'
```

2. Update version of the gradle wrapper in `android/gradle/wrapper/gradle-wrapper.properties` to:
```
distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-all.zip
```

Please @KeegsMcGeegs @nzhtrtlc @dantn93  let me know if this solves the issue so I can close this issue and include this as part of the Android's troubleshooting guide.

**Comment by jpgarcia** [comment]
**UPDATE:** Just found a real solution which is updating the `compileSdkVersion`,  `buildToolsVersion` and `targetSdkVersion` project's `build.gradle` 

I'll send a PR to fix the issue ASAP
