### ISSUE TITLE
Accessing AccountKitConfigurationBuilder

### ISSUE THREAD

**Issue by Quadriphobs1** [underscopeio/react-native-facebook-account-kit#149]
### Issue Description

Accessing the private method `AccountKitConfigurationBuilder` to custom configure the account functions. Especially `setInitialPhoneNumber`

### Steps to Reproduce / Code Snippets

Making the AccountKitConfigurationBuilder a public method and pass it to the javascript engine

### Additional Information

* Platform(s) (iOS, Android, or both?): both

**Comment by gaguirre** [comment]
Hi @Quadriphobs1, you can set the initial phone number using `initialPhoneNumber` field when calling `RNAccountKit.configure` method (see [here](https://github.com/underscopeio/react-native-facebook-account-kit#usage)).
Also you can set the `initialPhoneCountryPrefix` if necessary (will be automatically detected if not).

**Comment by Quadriphobs1** [comment]
Actually what I wanted was the option to show the phone number detected on device in modal and as the user to select which preferred to be pre-filled. I have seen it in several app which uses `account-kit` and I am wondering if that option would do it or I have to do the tweeking myself

**Comment by Quadriphobs1** [comment]
Even by setting
```
<uses-permission android:name="android.permission.READ_PHONE_STATE" />
    <uses-permission android:name="android.permission.RECEIVE_SMS" />
RNAccountKit.configure({
      facebookNotificationsEnabled: true,
      readPhoneStateEnabled: true,
      receiveSMS: true,
    });
```

the two options doesn't seems to work
