### ISSUE TITLE
 Manifest merger failed : Attribute application@allowBackup

### ISSUE THREAD

**Issue by jpgarcia** [underscopeio/react-native-facebook-account-kit#150]
### Issue Description

This is related to #136 and #146.

As mentioned [here](https://developers.facebook.com/docs/accountkit/accesstokens) Account Kit access tokens are not compatible with the auto backup feature introduced in Android 6.0 but **react-native-facebook-account-kit** `AndroidManifest.xml` [file](https://github.com/underscopeio/react-native-facebook-account-kit/blob/631ac920fce3819af1cd0b7825f55bfc36f05096/android/src/main/AndroidManifest.xml) has the `allowBackup` property set to **true**

In **react-native** version  **0.56.0** this property was changed from **true** to **false** in this [commit](https://github.com/facebook/react-native/commit/d7a9ca2893fb240c25d1cd1e0778f6b93b1e3ded#diff-ff5f45fe221d3130a374c986111920d4)  as considered as a not a secure config.

### Steps to Reproduce / Code Snippets

Create a new react-native project >= 0.56.0, perform Android's installation steps and you'll receive the following error:

```bash
* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:11:7-34
        is also present at [:react-native-facebook-account-kit] AndroidManifest.xml:12:9-35 value=(true).
        Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:7:5-33:19 to override.
```

#### Expected Results

Project compiles :)

### Additional Information

* React Native Account Kit version: 0.10.1
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): Android

**Comment by muralitharanaspritle** [comment]
Just remove the "application@allowBackup" at AndroidManifest.xml. It works for me.
