### ISSUE TITLE
[Android] App crashes when call to loginWithEmail/Phone

### ISSUE THREAD

**Issue by danhnguyeen** [underscopeio/react-native-facebook-account-kit#158]
### Issue Description
I installed and linked React Native Account Kit to my project. 
After fixed some issues, my app can start now.
But when i try to call to the loginWithEmail/Phone function, my app is crashed and auto closed.
Could you help me please?
Thank in advance!

**app/build.gradle**
dependencies {
    implementation project(':react-native-facebook-account-kit')
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:23.0.1"
    implementation "com.facebook.react:react-native:+"
    implementation project(':react-native-maps')
    implementation project(':react-native-splash-screen')
    implementation project(':react-native-linear-gradient')
    implementation project(':react-native-i18n')
    implementation project(':react-native-vector-icons')
    implementation project(':react-native-fcm')
    implementation 'com.google.firebase:firebase-core'
    implementation 'com.google.firebase:firebase-messaging'
}

**build.gradle**
ext {
    buildToolsVersion = "27.0.3"
    minSdkVersion = 16
    compileSdkVersion = 27
    targetSdkVersion = 27
    supportLibVersion = "26.1.0"
    googlePlayServicesVersion = "15.0.1"
    androidMapsUtilsVersion = "0.5+"
}

### Additional Information

* React Native Account Kit version: "0.11.0"
* React Native version: "0.55.4"
* Platform(s) (iOS, Android, or both?): Android

**Comment by jpgarcia** [comment]
Hi @danhnguyeen we need the logs to see what is happening. Could you please run `adb logcat` when launching the app or get the logs from Android Studio? and post here the output?

**Comment by danhnguyeen** [comment]
Hi @jpgarcia , thanks for you fast reply. I tried `adb logcat`, but i'm not sure it's useful. Because when the app is crashed, it doesn't log anything

> 10-02 17:54:51.693  9325  9325 D ReactNative: ReactInstanceManager.onJSBundleLoadedFromServer()
10-02 17:54:51.694  9325  9325 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
10-02 17:54:51.694  9325  9325 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
10-02 17:54:51.694  9325  9325 D ReactNative: ReactInstanceManager.tearDownReactContext()
10-02 17:54:51.696  9325  9325 D ReactNative: CatalystInstanceImpl.destroy() start
10-02 17:54:51.698  9325  9541 D ReactNative: ReactInstanceManager.createReactContext()
10-02 17:54:51.814  9325  9508 D ReactNative: CatalystInstanceImpl.destroy() end
10-02 17:54:51.829  9325  9541 D ReactNative: Initializing React Xplat Bridge.
10-02 17:54:51.830  9325  9541 D ReactNative: Initializing React Xplat Bridge before initializeBridge
10-02 17:54:51.837  9325  9541 D ReactNative: Initializing React Xplat Bridge after initializeBridge
10-02 17:54:51.837  9325  9541 D ReactNative: CatalystInstanceImpl.runJSBundle()
10-02 17:54:51.837  9325  9543 D ReactNative: ReactInstanceManager.setupReactContext()
10-02 17:54:51.837  9325  9543 D ReactNative: CatalystInstanceImpl.initialize()
10-02 17:54:51.838  9325  9543 D ReactNative: ReactInstanceManager.attachRootViewToInstance()
10-02 17:54:54.017  9325  9542 I ReactNativeJS: Running application "mylife_app" with appParams: {"rootTag":21}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
10-02 17:54:54.364  9325  9542 I ReactNativeJS: No user account logged
10-02 17:55:06.490  9325  9542 I ReactNativeJS: login with email

**Comment by danhnguyeen** [comment]
@jpgarcia  ah sorry, i have just re-edit the `logcat`

**Comment by jpgarcia** [comment]
Not really sure but It seems there's a conflict with the `supportLibVersion`... did you try upgrading it to `27.1.1`?

**Comment by danhnguyeen** [comment]
yes, that is exactly what i think. i think there are some conflict versions. i tried 27.1.1, but still same problem :(

**Comment by jpgarcia** [comment]
Sorry to hear that 😞 Maybe if you create a sample in a public repo with the issue, I can help you to troubleshoot the issue...

**Comment by jpgarcia** [comment]
You can also try by overriding the dependencies as I mentioned in this [issue](https://github.com/underscopeio/react-native-facebook-account-kit/issues/157#issuecomment-423949726) to workaround firebase dependencies using `resolutionStrategy`.

**Comment by danhnguyeen** [comment]
@jpgarcia  i have just public my repo.
if you have time, can you help me please.
Really big thanks for that
https://github.com/amagumolabs/mylife-app-v2

branch `feat/facebook-account-kit ` please

**Comment by jpgarcia** [comment]
I tried the branch you mentioned but the application bundle is throwing errors. Could you please check that? maybe you forgot to commit something.

```
Error: Unable to resolve module `./BookingData` from `~/mylife-app-v2/src/components/BookTable/TabBooking/BookingForm/index.js`: The module `./BookingData` could not be found from `~/mylife-app-v2/src/components/BookTable/TabBooking/BookingForm/index.js`. Indeed, none of these files exist:
```

**Comment by danhnguyeen** [comment]
ah yes, the reason is Git doesn't update when i rename the files from lowercase to uppercase.
i have just disabled that modules. Could you re-pull the repo please

**Comment by danhnguyeen** [comment]
sorry for that. Because it's working on my computer. 
i have just renamed the files same with Git repo.
it should be ok now

**Comment by jpgarcia** [comment]
Hey @danhnguyeen just got your app working with account kit by adding the following dependency to the `dependencies` section in `android/app/build.gradle` file.

`implementation "com.android.support:design:27.1.0"`

Let me know if it did the trick so I can close this one.

**Comment by danhnguyeen** [comment]
My god, it's worked perfectly.
Your support is really saved my time too much.
Big thanks for your support.
Wish all the best for you, @jpgarcia

**Comment by bijoycse** [comment]
_I have solved it by simply down grade the version of react-native-facebook-account-kit as well as add implementation "com.android.support:design:27.1.0"_
--------------------------------------------------------------------------------
before : "react-native-facebook-account-kit": "^1.0.2"

now : "react-native": "0.57.8",
"react-native-facebook-account-kit": "^0.11.0",
"react-native-firebase": "^5.1.0"

**its working now along with triangle integration 1. react-native-maps 2. react-native-fire-base 3. react-native-facebook-account-kit**

**Comment by phanbien9x** [comment]
@bijoycse Can you create release apk? I follow your recommend but when release it not work.
My logcat: 
```
D:\WORKSPACE\REACT_PROJECT\vtgo_owner\VTGO\node_modules\react-native-facebook-account-kit\android\build\intermediates\res\compiled\release\values_values.arsc.flat\
          -R\
          D:\WORKSPACE\REACT_PROJECT\vtgo_owner\VTGO\node_modules\react-native-facebook-account-kit\android\build\intermediates\res\compiled\release\xml_preferences.xml.flat\
          --auto-add-overlay\
          --non-final-ids\
          -0\
          apk\
          --no-version-vectors
  Daemon:  AAPT2 aapt2-3.2.1-4818971-windows Daemon #0
```

**Comment by bijoycse** [comment]
@phanbien9x 
**Please add this line android/build.gradle**

```
subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 27     //do this in android/app/build.gradle too
                buildToolsVersion '27.0.3'  //do this in android/app/build.gradle too
            }
        }
    }
}
```

**Comment by phanbien9x** [comment]
@bijoycse Did you try #157 solution. I don't know how to implement that!

**Comment by bijoycse** [comment]
@phanbien9x 
Yes i use react-native-firebase so please go through and [this link](https://medium.com/@yangnana11/how-to-set-up-firebase-notification-in-react-native-app-android-only-4920eb875eae) and implement.

**Comment by phanbien9x** [comment]
Thank you @bijoycse. I tried but it hard to implement!

**Comment by bijoycse** [comment]
@phanbien9x 
Yes i use react-native-firebase so please go through and [this link](https://medium.com/@yangnana11/how-to-set-up-firebase-notification-in-react-native-app-android-only-4920eb875eae) and implement.
