### ISSUE TITLE
Difference between iOS and Android

### ISSUE THREAD

**Issue by Nopik** [underscopeio/react-native-facebook-account-kit#16]
It seems that `RNAccountKit.loginWithPhone()` for `responseType: 'code'` configuration does return string on iOS (being the code returned), but `{ state: '', code: "..." }` kind of object on Android. It would be great if react-native-facebook-account-kit would provide consistent API across platforms.

**Comment by gaguirre** [comment]
Hi @Nopik, thanks for submitting the issue.
The recently published version **0.3.0** fixes that.

**Comment by Nopik** [comment]
Thanks, I'll check it out.
