### ISSUE TITLE
Auto Detection of SMS Verification Code not working

### ISSUE THREAD

**Issue by iamammar1** [underscopeio/react-native-facebook-account-kit#162]
I'm using the latest version of react-native-facebook-account-kit and Auto Detection of SMS Verification Code is not working.

**Comment by jpgarcia** [comment]
Just tried with latest version and it worked! 

Did you check the Android section (step 3) [Configuration section](https://github.com/underscopeio/react-native-facebook-account-kit#configuration). Maybe you're not setting the `READ_SMS`, `RECEIVE_SMS `, `READ_PHONE_STATE ` permissions?

I'm closing this. If you are still facing the issue, please complete the ISSUE template with the required data (RN version / AccountKit version / Android Device version etc... ) so we can try to reproduce the issue.

Thanks
