### ISSUE TITLE
Phone number not getting autofilled

### ISSUE THREAD

**Issue by jose2007kj** [underscopeio/react-native-facebook-account-kit#163]
### Issue Description

[Phone number not getting auto filled in android]

### Steps to Reproduce / Code Snippets

[added the permission in manifest file for read phone state]

#### Expected Results

[phone number field gets auto filled instead of user typing it]

### Additional Information

* React Native Account Kit version: [^0.9.3]
* React Native version: [0.57.0]
* Platform(s) (iOS, Android, or both?): [Android]
* Platform Version(s): [android version 5.1.1(lollipop)]

**Comment by nil1511** [comment]
Set accountKitSdkVersion to 4.29.0 in root build.gradle 
`setInitialPhoneNumber` is not working after 4.29.0 

```gradle
ext {
    accountKitSdkVersion = '4.29.0'
}
```

**Comment by jose2007kj** [comment]
thanks @nil1511 i will check

**Comment by jose2007kj** [comment]
@nil1511 on changing the account kitsdk version in ```
node_modules/react-native-facebook-account-kit
/android/build.gradle
```
my app crashed, where i might be going wrong

**Comment by nil1511** [comment]
@jose2007kj update in PROJECT_FOLDER/android/build.gradle not in node_modules.

**Comment by jose2007kj** [comment]
hi @nil1511 sorry, it seems its because i need to request runtime permission for new versions of android..... once again thanks
