### ISSUE TITLE
Callbacks for back and other buttons

### ISSUE THREAD

**Issue by iadcg** [underscopeio/react-native-facebook-account-kit#169]
How to have callback on the button clicks in the verify code page.
Basically I want to know when the user click "I didnt receive a code" button.
So when the user clicks this button, I want to do some loggings or other stuff.

Also I want to know if user press back button instead and did not continue on the screen.

![fb-accountkit](https://user-images.githubusercontent.com/45412363/49979243-261f7b80-ff89-11e8-8141-2d5fc86de3cd.png)

**Comment by jpgarcia** [comment]
AFAIK the AccountKit library does not provide callback for internal events. You only get access to the login result, cancelled state and error through the callback.
