### ISSUE TITLE
Property enbaleGetACall not found on object of type UIViewController<AKFViewController>

### ISSUE THREAD

**Issue by lex-github** [underscopeio/react-native-facebook-account-kit#174]
### Issue Description

Fresh project, after installing toolkit ios project does not compile with the error above

### Additional Information

* React Native Account Kit version: 1.0.x
* React Native version: 0.57
* Platform(s) (iOS, Android, or both?): iOS
* Platform Version(s): 9.3 (9E145)

![screenshot 2019-01-21 19 00 45](https://user-images.githubusercontent.com/3257119/51486034-aae38d80-1db0-11e9-8eb2-e7adce33e742.png)

**Comment by lex-github** [comment]
checked in latest xcode and still not working

**Comment by Tebrynn** [comment]
Same problem here. Tried to relink

**Comment by lex-github** [comment]
commenting the line out is enough to get it working though

**Comment by tmjordan** [comment]
i had the same problem, and what i did: after the build failed, i closed xcode and i relaunched it, and as soon as it get started, i relaunched the build and it worked. i tried 3 times.
it is not a fix, but maybe it can help you

**Comment by tmjordan** [comment]
you have to also clean the project

**Comment by tmjordan** [comment]
@lex-github if you do that you won't be able to use phone call to receive verification code.
The problem seems to be related to xcode. Sometimes builds succeed sometimes not.

**Comment by HoangThongBui** [comment]
I got this error only when running on real device but Simulator is fine.
What I did: comment the line `viewController.enableGetACall = self.getACallEnabled;` in `RNAccountKitViewController.m` and it worked.

**Comment by jpgarcia** [comment]
The issue is because current's AK version included in this project does not include that feature.

I'm about to publish a new version that should fix the issue. I'll keep you posted here.

Thanks for all the feedback

**Comment by jpgarcia** [comment]
I've just published a new version `1.1.0` which upgrades the AK framework to the latest version `4.40.0` for IOS and `4.+` for Android (currently `4.39.0`).

If you are NOT using `Cocoapods` and linked this library manually I must do the following steps:

1. Open your project with XCode
2. Remove the `AccountKit.framework` and `AccountKitStrings.bundle` references from your project
3. Follow the steps described in the updated [Readme](https://github.com/underscopeio/react-native-facebook-account-kit#ios-without-cocoapods-not-recomended). 
   - Make sure you  **unselect** the "Copy items if needed". 
   - Configure `Framework Search Paths`

Let me know if you found any issues
