### ISSUE TITLE
Android Customization

### ISSUE THREAD

**Issue by stief510** [underscopeio/react-native-facebook-account-kit#18]
How do you customize the colors for Android?

**Comment by zevmo** [comment]
+1

**Comment by gaguirre** [comment]
Android customization programatically (like iOS) is not possible.
You will need to create a custom theme. Check this link https://developers.facebook.com/docs/accountkit/android/customizing

**Comment by stief510** [comment]
Yes, I added that theme to styles.xml and referred to it in AndroidManifest.xml to no avail.

Where exactly should it be put? Is there a specific format it requires?

**Comment by gaguirre** [comment]
I'll try it and tell you. Probably an extra line is required on Android side setting the theme resource created in **styles.xml**. Pull request are welcome also ;)

**Comment by stief510** [comment]
Any update on this?

**Comment by gaguirre** [comment]
@stief510 yes, good ones! I'll update the documentation in a few minutes.
