### ISSUE TITLE
Verifying the Phone Number

### ISSUE THREAD

**Issue by srichallamalla935** [underscopeio/react-native-facebook-account-kit#183]
** Issue Description **

In Android devices Screen **get Strucked in the Verifying Phone Number Screen** .Device is getting the otp  but it is showing loading sign that verifying the number and the screen remains  without opening the otp screen

** Additional Information

> React Native Account Kit version:1.1.0
> React Native version: 0.57.3

** Code Snippets

```
  fbLogin() {
    RNAccountKit.configure({
      theme: {
        buttonBackgroundColor: Color.hex("#FF2929"),
        buttonBorderColor: Color.hex("#FF2929"),
        buttonTextColor: Color.hex("#fff"),
    }
    });
    RNAccountKit.loginWithPhone()
      .then(token => {
        if (!token) {
          Alert.alert(
            "UrbanRider Business",
            "Please Login Again",
            [{ text: "OK", onPress: () => this.fbLogin() }],
            { cancelable: false }
          );
        } else {
          console.log(`TokeFFFFFFFNNNNNn: ${JSON.stringify(token)}`);
          this.getCurrentPhone();
        }
      })
      .catch(error => {
        Alert.alert(
          "UrbanRider Business",
          "Please Login Again",
          [{ text: "OK", onPress: () => this.fbLogin() }],
          { cancelable: false }
        );
      });
  }
  getCurrentPhone() {
    AccountKit.getCurrentAccount().then(account => {
      console.log("account1234", JSON.stringify(account));
      mobileNumberFb = account.phoneNumber.number;
      this.setState(
        {
          loggedAccount: account.phoneNumber
        },
        () => {
          this.onLogin(account.phoneNumber);
        }
      );
      console.log("account" + JSON.stringify(this.state.loggedAccount));
    });
  }
```

** Expected Results

Otp Screen should be opened to enter the otp 

![Screenshot_2019-04-03-15-46-11-611_com urbanriderbusiness](https://user-images.githubusercontent.com/45194188/55528398-4a2ed600-56ba-11e9-9b8c-a3f07aa4ddee.png)

**Comment by jpgarcia** [comment]
I've performed some tests and the library is working as expected. Maybe there was a temporary issue with account kit at that moment.

Feel free to re-open the issue if you're still facing the same behavior but ideally you should provide a public repo to be able to troubleshoot it.

Thanks
