### ISSUE TITLE
TypeError : Network Request Failed

### ISSUE THREAD

**Issue by chandrabudiman** [underscopeio/react-native-facebook-account-kit#184]
### Issue Description
I had success run the tutorial PART 1 - 3 from below link,  
[PART 1](https://medium.com/react-native-training/passwordless-authentication-in-react-native-using-facebook-account-kit-part-1-8d83e92077e9)
[PART 2](https://medium.com/react-native-training/passwordless-authentication-in-react-native-using-facebook-account-kit-part-2-367a820f269c)
[PART 3](https://medium.com/react-native-training/passwordless-authentication-in-react-native-using-facebook-account-kit-part-3-ddf44d81beb5)
.
Then I implement it into my Dev file and success as well.
.
Unfortunately, After a week, I got the error.
I had tried Dev file and tutorial file, both got the same error.
.
When I run the app,
1. Login Button
2. Request Phone Number
3. Insert SMS Code from Facebook
4. Back to Login Button
![errorResult](https://user-images.githubusercontent.com/32405147/55665817-d3d3d480-586f-11e9-9747-b7b55ed767d9.png)
.
Then, I put console warn to find out what happen, I got this : **TypeError: Network Request Failed.** . This console.warn appear at fourth step ( back to login button ).
![error](https://user-images.githubusercontent.com/32405147/55665455-2a3e1480-586a-11e9-8e60-be6560ea9071.jpg)
.
### Steps to Reproduce / Code Snippets
[PART 1](https://medium.com/react-native-training/passwordless-authentication-in-react-native-using-facebook-account-kit-part-1-8d83e92077e9)
[PART 2](https://medium.com/react-native-training/passwordless-authentication-in-react-native-using-facebook-account-kit-part-2-367a820f269c)
[PART 3](https://medium.com/react-native-training/passwordless-authentication-in-react-native-using-facebook-account-kit-part-3-ddf44d81beb5)
.
#### Expected Results
1. Login Button
2. Request Phone Number
3. Insert SMS Code from facebook
4. Show Welcome Screen    // expected
![expectResult](https://user-images.githubusercontent.com/32405147/55665444-fbc03980-5869-11e9-8d27-474b9a968946.png)

### Additional Information

* React Native Account Kit version: 1.1.0
* React Native version: 0.59.2
* Platform(s) (iOS, Android, or both?): Android
* Platform Version(s): 22

How do I fix this ?
Thanks in advance.

**Comment by chandrabudiman** [comment]
I change to another Internet WIFI network then it WORKS..
I dont know what happen here.
I spend 3 hours to find out the problem.

**Comment by safciplak** [comment]
i encountered but no way. i didn't fix it still. can we reopen the issue ?
