### ISSUE TITLE
App Store Warning "Unrecognized Locale", and sometimes Facebook don't send the login code

### ISSUE THREAD

**Issue by danhnguyeen** [underscopeio/react-native-facebook-account-kit#186]
### Issue Description
First, I don't know why but in some cases, the Facebook didn't send the login code to me. Even when I tried to login again many times, but I still didn't receive the code.

But in the rest cases, it often works well. I was wondering if you would give me some advice for this case please?

And the second thing, I have just upgraded the latest `react-native-facebook-account-kit` version, everything is ok.
But after I submitted my app to App Store, the Xcode shown the warning, and Apple sent to me an email as below 
```
WARNING ITMS-90176: "Unrecognized Locale - The locale names used in localization directories at ( "Payload/MylifeCompany.app/AccountKitStrings.bundle/Resources/cb_IQ.lproj" ) are invalid. 
iTunes supports BCP47 but not the UN M.49 specification. Refer to the Language and Locale 
Designations guide at https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html for more information on naming your language-specific directories."
```

Could you tell me how to fix please?
Many thanks!

### Additional Information

* React Native Account Kit version: 1.1.0
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): iOS

**Comment by danhnguyeen** [comment]
About the `Unrecognized Locale` warning, it seems I just need to remove the `ckb_IQ.lproj` package in `AccountKitStrings.bundle/Resources`?

**Comment by jpgarcia** [comment]
@danhnguyeen Sometimes **Account Kit** doesn't deliver SMS properly maybe that's why you didn't receive the code 😢

Regarding the second issue it seems that the latest version of the SDK doesn't include the file you removed. You can check here ([check here](https://github.com/facebook/facebook-objc-sdk/tree/master/FacebookSDKStrings.bundle/Resources))

You can try with the fresh new **1.2.0** version of this library which also allows you to send verification messages through **Whatspp**!

Thanks!

**Comment by anhtuank7c** [comment]
I facing the same issue in version `2.0.0`.
Any tips to resolve it?
```
WARNING ITMS-90176: "Unrecognized Locale - The locale names used in localization directories at ( "Payload/myapp.app/AccountKitStrings.bundle/Resources/cb_IQ.lproj" ) are invalid. iTunes supports BCP47 but not the UN M.49 specification. Refer to the Language and Locale Designations guide at https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html for more information on naming your language-specific directories."
```
