### ISSUE TITLE
Update Accountkit Sdk to v5

### ISSUE THREAD

**Issue by seunlanlege** [underscopeio/react-native-facebook-account-kit#187]
the new sdk supports whatsapp verification

**Comment by sunshineo** [comment]
I needed to do this for Android only, so I created this https://github.com/underscopeio/react-native-facebook-account-kit/pull/190 . I can say it works for me on Android

Hope someone else can do it for iOS

**Comment by kevinkevw** [comment]
I am not 100% sure, but current version on iOS already supports whatsApp OTP in my case.

**Comment by adarsh431** [comment]
Hi @kevinkevw can you please share the changes you did to support WhatsApp OTP. 
I am getting the SMS but not receiving the OTP on WhatsApp.

**Comment by adarsh431** [comment]
for iOS developers with RN < 0.48, you just need to replace the accountKit with latest version.

**Comment by kevinkevw** [comment]
> Hi @kevinkevw can you please share the changes you did to support WhatsApp OTP.
> I am getting the SMS but not receiving the OTP on WhatsApp.

I didn't change anything. I just use 1.1.0 and link with Cocoapod. didn't even call RNAccountKit.configure().

**Comment by jpgarcia** [comment]
Guys, we just published a new npm version (1.2.0) of the library which upgrades the SDK to 5.+ for **Android** and **IOS**
