### ISSUE TITLE
App keeps stopping (React Native v.0.59.8)

### ISSUE THREAD

**Issue by dimgrav** [underscopeio/react-native-facebook-account-kit#188]
### Issue Description

App keeps stopping on emulator (API 27-28) and physical device (API 28).

_React Native version used is newer than the latest supported version._

### Steps to Reproduce / Code Snippets

With AVD installed and properly configured:

```
yarn add react-native-facebook-account-kit
react-native link react-native-facebook-account-kit
emulator @emulator_name
yarn run start --reset-cache
react-native run-android
```

#### Expected Results

The app should start and stay open until dismissed.

### Additional Information

* React Native Account Kit version: 1.1.0
* React Native version: 0.59.8
* Platform(s) (iOS, Android, or both?): Android
* Platform Version(s): Oreo (API 27), Pie (API 28)

Found in `io.underscope.react.fbak.RNAccountKitModule`:
```java
boolean receiveSMS = this.options.getBoolean("receiveSMS");
if (receiveSMS && PackageManager.PERMISSION_DENIED == ContextCompat.checkSelfPermission(
                reactContext.getApplicationContext(), Manifest.permission.RECEIVE_SMS)) {
    Log.w(REACT_CLASS, "To allow extracting code from SMS add RECEIVE_SMS permission in your app's manifest");
            configurationBuilder.setReceiveSMS(false);
} else {
    configurationBuilder.setReceiveSMS(receiveSMS);
}
```
`AccountKitConfiguration` class does not implement `setReceiveSms()` anymore.

**Comment by dimgrav** [comment]
Closed, as there was misconfiguration elsewhere, from my part.

**Comment by jxnata** [comment]
Hi, I have the same problem. How did you solve it?
