### ISSUE TITLE
callback for cancel

### ISSUE THREAD

**Issue by laychar** [underscopeio/react-native-facebook-account-kit#189]
### Issue Description

I want make my app  execute some code right after users cancel sign in.

For example my app's login page has several options for sign in method such as facebook login , phone verification etc...
If a user who want to sign in by verifying email select phone verification by mistake, he or she will cancel verifying phone and go back to login page to select email verification button.
I want to know how to execute callback function about canceling sign in.

**Comment by anniewey** [comment]
@laychar As mentioned in doc,

```
RNAccountKit.loginWithPhone()
  .then((token) => {
    if (!token) {
      console.log('Login cancelled')
      //perform your callback here
    } else {
      console.log(`Logged with phone. Token: ${token}`)
    }
  })
```
