### ISSUE TITLE
auto change language

### ISSUE THREAD

**Issue by 2ducanhpham** [underscopeio/react-native-facebook-account-kit#19]
Automatic way to change the language when the application STATE changes?

**Comment by gaguirre** [comment]
Hi @2ducanhpham, what do you mean with _application STATE_?
The **AKFLoginFlowState** or your React application state?

**Comment by 2ducanhpham** [comment]
hi @gaguirre , **React application state**.
 I have 2 languages : US, VN. i want auto change language when i choose language, thanks!

**Comment by gaguirre** [comment]
There is no response field for the language used in the AccountKit flow.

However, you could use the country code selected when filling the phone number (in case of SMS) and use it to set the language in your application. Or maybe you can get it from the Facebook Graph using the obtained access token.
