### ISSUE TITLE
[AKFNavigationController setUiManager:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by tombaki** [underscopeio/react-native-facebook-account-kit#191]
### Issue Description

while click sms for login app crash with 

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AKFNavigationController setUiManager:]: unrecognized selector sent to instance

### Steps to Reproduce / Code Snippets

click sms button make app crash with 

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AKFNavigationController setUiManager:]: unrecognized selector sent to instance

#### Expected Results

crashed app with 
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AKFNavigationController setUiManager:]: unrecognized selector sent to instance

### Additional Information

* React Native Account Kit version: ^1.1.0
* React Native version:^0.57.4
* Platform(s) (iOS, Android, or both?): ios
* Platform Version(s): 12.3

**Comment by minhchienwikipedia** [comment]
@tombaki Did you resolve it? How do you do it? I get the same issue, can you help me?

**Comment by dannyyaou** [comment]
Same here...
