### ISSUE TITLE
App crash when navigating to account kit page

### ISSUE THREAD

**Issue by TheJackTenor** [underscopeio/react-native-facebook-account-kit#193]
### Issue Description

I had experienced crash app when i try to go to Account Kit page

### Steps to Reproduce / Code Snippets

1. Go To Account Kit Page
2. App Crash
3. Error message: 'NSInvalidArgumentException', reason: '-[AKFNavigationController setUiManager:]: unrecognized selector sent to instance 0x7f85150a5200'

#### Expected Results

Account Kit page should be show

### Additional Information

* React Native Account Kit version: 1.1.0
* React Native version: 0.59
* Platform(s) (iOS, Android, or both?): iOS
* Platform Version(s):

**Comment by jpgarcia** [comment]
I've just created a project from scratch with the same configuration and worked. Could you please provide a public repo with the app crashing? thanks!

I'm closing this for now
