### ISSUE TITLE
Skip input phone step

### ISSUE THREAD

**Issue by minhquankq** [underscopeio/react-native-facebook-account-kit#198]
## Hey there! I'm not sure if it's an issue
Example I've already inputed phone number in my form and I want to request code and input code screen without input phone number screen, because I have configured `initialPhoneNumber`, example

```
RNAccountKit.configure({
      responseType: 'token',
      initialPhoneCountryPrefix: AppKey.PhoneCode,
      defaultCountry: AppKey.CountryCode,
      initialPhoneNumber: '0909999888', // TODO will be get from navigation props
    });
```

Can I do that?

**Comment by jpgarcia** [comment]
Hi @minhquankq but I think that what you want to achieve is not possible. 

As described in the documentation the initialPhone number is just to *"pre-fill the user's phone number in the SMS login flow."*

You can check the docs here https://developers.facebook.com/docs/accountkit/android/accountkitconfigurationbuilder/
