### ISSUE TITLE
cannot find symbol import io.underscope.react.RNAccountKit;

### ISSUE THREAD

**Issue by Keishee** [underscopeio/react-native-facebook-account-kit#20]
>  error: cannot find symbol
import io.underscope.react.RNAccountKit;
symbol:   class RNAccountKit
  location: package io.underscope.react
error: cannot find symbol
            new RNAccountKit(),
                ^
  symbol:   class RNAccountKit
  location: class MainActivity

I followed the manual installation for Android

**Comment by gaguirre** [comment]
Hi @Keishee, there is a typo in the documentation.
```java
// use 
import io.underscope.react.fbak.RNAccountKitPackage;
// instead of
import io.underscope.react.RNAccountKitPackage;
```

Thanks for submitting the issue!

**Comment by Keishee** [comment]
Thank you,

as a following to that, I guess
>new RNAccountKit()

should be 
>new RNAccountKitPackage()

right?

**Comment by gaguirre** [comment]
Right! Thank you
