### ISSUE TITLE
Could not invoke RNAccoutKit.login

### ISSUE THREAD

**Issue by duyv** [underscopeio/react-native-facebook-account-kit#202]
This error appear when I call RNAccountKit login method (by phone or by email). I was try to change version from 1.2.0 to 2.1.0 but not work. I think something wrong around method **setEnableInitialSmsButton**. 

```
Could not invoke RNAccountKit.login

null

No virtual method setEnableInitialSmsButton(Z)Lcom/facebook/accountkit/ui/AccountKitConfiguration$AccountKitConfigurationBuilder; in class Lcom/facebook/accountkit/ui/AccountKitConfiguration$AccountKitConfigurationBuilder; or its super classes (declaration of 'com.facebook.accountkit.ui.AccountKitConfiguration$AccountKitConfigurationBuilder' appears in /data/app/com.test.accountkit-2/base.apk)
```

**Comment by sinhpn92** [comment]
Fix specific your accountkit version to 5.0.1

**Comment by saurabhjayx** [comment]
or in build.gradle you can set 
`implementation 'com.facebook.android:account-kit-sdk:5+'`
to 
`implementation 'com.facebook.android:account-kit-sdk:5.0.0'`

**Comment by pankti1210** [comment]
@saurabhjayx  this solution is not working..!

**Comment by tungmt** [comment]
@saurabhjayx it worked for me

**Comment by jpgarcia** [comment]
Closing this as it seems to be a misconfiguration issue. 

Feel free to reopen it but provide a detailed issue by filling out the template suggested by the issue creation form.
