### ISSUE TITLE
Unable to Run the project on iOS v2.1.0 TypeError: null is not an object (evaluating 'RNAccountKitNative.ANY_FUNCTION) on iOS

### ISSUE THREAD

**Issue by shibbyy** [underscopeio/react-native-facebook-account-kit#203]
# Issue Description

TypeError: null is not an object (evaluating 'RNAccountKitNative.configure')

### Steps to Reproduce / Code Snippets

Updated RN to 0.60.4 and updated react-native-facebook-account-kit from "^0.9.3" -> "2.1.0"

#### Expected Results

Everything seems to work fine on Android, but I get the null is not an object (evaluating 'RNAccountKitNative.configure') on iOS

### Additional Information

* React Native Account Kit version: 2.1.0
* React Native version: 0.60.4
* Platform(s) (iOS, Android, or both?): iOS Only

<img width="364" alt="Screenshot 2019-08-22 at 3 50 51 PM" src="https://user-images.githubusercontent.com/18098554/63548876-d9933380-c54c-11e9-862f-ab431e666829.png">

**Comment by shibbyy** [comment]
Do we have an update here please? @jpgarcia

**Comment by jpgarcia** [comment]
Sorry for the late response @shibbyy I've been quite busy lately. 

I tried the reproduce the issue you mention and even tough I worked I noticed that maybe you have forgotten to run `pod install` from the `ios` folder after doing `yarn add react-native-facebook-account-kit`.

I'll close this issue and will add a note to the readme file.

Thanks for reporting this and I hope my suggestion work on your side.

**Comment by shibbyy** [comment]
Hi @jpgarcia thanks for the reply.
I did run pod install after running the command npm i -s react-native-facebook-account-kit

Can you please recheck? Maybe an issue with deleting something from the Xcode workspace, worked as expected on Android.
