### ISSUE TITLE
Auto linking not working on android

### ISSUE THREAD

**Issue by pankti1210** [underscopeio/react-native-facebook-account-kit#205]
version: 
"react": "16.8.6",
"react-native": "0.60.5",
 "react-native-facebook-account-kit": "^2.1.0"

app builds but as soon as i open the app it gets crash.. it gets closed immediately without any error..
it happens after installing this package..
Please help..

**Comment by jpgarcia** [comment]
Just tried to reproduce the issue by creating a sample with the same configuration you provided but it worked like a charm 🤷‍♂

I'm closing this for now. In case you still facing the same issue please provide us a detailed log using `adb logcat` or even better a public repository with the project failing so we can help you to troubleshoot it
