### ISSUE TITLE
[Question] Is it possible to show the viewConroller from right to left instead of from bottom to top (Like modal)

### ISSUE THREAD

**Issue by iwantooxxoox** [underscopeio/react-native-facebook-account-kit#206]
### Issue Description

Hi, I'm wondering if it's possible to show the view controller from left right, like navigation instead of a bottom-up pop modal. I have tried to set viewControllerMode: 'show', but seems not working. 

* React Native Account Kit version: 1.1.0
* React Native version: 0.59.8
* Platform(s) (iOS, Android, or both?): both

**Comment by jpgarcia** [comment]
Nope, the library doesn't support that feature right now on the other side I'm not sure if there is a limitation on the AK Sdk. 

Feel free to send a PR if you find a way to do that.
Thanks
