### ISSUE TITLE
A System issue occured. Please Try again

### ISSUE THREAD

**Issue by MahbbRah** [underscopeio/react-native-facebook-account-kit#209]
![Error With Account Kit](https://user-images.githubusercontent.com/10045253/65385352-a8767080-dd4f-11e9-9c9b-b4e03463f2b5.png)

I was using account kit with a existing project. then moved to RN .60. where it was still working perfectly. I think since 3-4 days. account kit not working and logging like that above when I put phone number. 

I even tried with a fresh install with only account kit and RN .60. still faces that issue. 

Somebody, please have a look on it.

**Comment by helloagain-dev** [comment]
We have the same Issue.
react-native: 0.59
react-native-facebook-account-kit: 1.1.0

This only occurs for some users and it seems that it started a few days ago.

**Comment by MahbbRah** [comment]
> 
> 
> We have the same Issue.
> react-native: 0.59
> react-native-facebook-account-kit: 1.1.0
> 
> This only occurs for some users and it seems that it started a few days ago.

Hey, I was able to figure this problem. It was because of internet connection. If you have a bad connection/ip/internet then this problem occurs due to blacklisted  internet service provider IP's this problem happens. there is nothing to do here.
