### ISSUE TITLE
Status bar style

### ISSUE THREAD

**Issue by stief510** [underscopeio/react-native-facebook-account-kit#21]
Is there a way to override the status bar style?

**Comment by gaguirre** [comment]
Working on it! I'll tell you when finished.

**Comment by gaguirre** [comment]
No luck with this one :(

The Account Kit SDK has a method to set it but it's not working. 
At least I can't see any change: the status text color remains the same, the background color does not change either. That should change, right?

**Comment by gaguirre** [comment]
@stief510 please give it a try and re-open if not solved.
I just submit an issue [here](https://developers.facebook.com/bugs/289019551448683/) related to this.

**Comment by stief510** [comment]
@gaguirre Awesome, thanks so much! I'll give it a try.

**Comment by gaguirre** [comment]
Hi @stief510, I've some updates on this.
To see reflected the status bar style you must set the **UIViewControllerBasedStatusBarAppearance** property to **true** on your app's _Info.plist_ file

<img width="507" alt="screen shot 2016-08-02 at 11 44 07 am" src="https://cloud.githubusercontent.com/assets/1652196/17332979/0fa632b2-58a7-11e6-9aa3-a669ae44f2e6.png">

See the **LightContent** status bar style working

<img width="423" alt="screen shot 2016-08-02 at 11 47 14 am" src="https://cloud.githubusercontent.com/assets/1652196/17333095/67206698-58a7-11e6-8800-e2b52264967e.png">
