### ISSUE TITLE
Any onBackPress callback??

### ISSUE THREAD

**Issue by zsajjad** [underscopeio/react-native-facebook-account-kit#22]
```
      AccountKit.loginWithPhone()
        .then((code) => {
          if (!code) {
            self.endLoading();
            return;
          } else {
            .......
          }
        }).catch(() =>{
          self.endLoading();
        });
```
Code in catch() is running on android but on iOS its not executing can you please check!

**Comment by gaguirre** [comment]
I debugged it but no callback is called on native side when _Back_ button is pressed.
I will look if there is a new Account Kit Framework version that fixes that (when have time).

**Comment by gaguirre** [comment]
@zsajjad this is a Account Kit bug already reported [here](https://developers.facebook.com/bugs/1631609907166073/). I just subscribed to it and will fix this issue when possible.

**Comment by gaguirre** [comment]
Fixed in new Android SDK release. Re-building the project should fix the issue.
