### ISSUE TITLE
check Android readPhoneState logic

### ISSUE THREAD

**Issue by fabriziomoscon** [underscopeio/react-native-facebook-account-kit#23]
@gaguirre is this logic correct?
https://github.com/underscopeio/react-native-facebook-account-kit/blob/master/android/src/main/java/io/underscope/react/fbak/RNAccountKitModule.java#L213-L219

I am not able to prefill the user phone number even though I follow the instructions:

> If people grant the READ_PHONE_STATE permission, the SDK can automatically fill in the device’s phone number. People still need to manually submit their phone number to continue the login process
> Add the following permission to AndroidManifest.xml to allow the SDK to auto-fill the device's phone number:
`<uses-permission android:name="android.permission.READ_PHONE_STATE" />`

```
RNAccountKit.configure({
        responseType: 'token',
        titleType: 'login',
        initialAuthState: '',
        facebookNotificationsEnabled: true,
        readPhoneStateEnabled: true,
        receiveSMS: true,
        defaultCountry: 'GB'
    })
```

**Comment by gaguirre** [comment]
@fabriziomoscon there are [some caveats](http://stackoverflow.com/a/2480307/3791502) related to this.
Are you using a real device to test it?

**Comment by fabriziomoscon** [comment]
Yes I am using a Nexus 4

**Comment by gaguirre** [comment]
I just tested in a _Moto E_ and it's working. I'm closing this issue since it's related to the device configuration, not this library.

See the comments on the link posted above for more info.
