### ISSUE TITLE
[Question] best practice for backend/code authentication

### ISSUE THREAD

**Issue by fabriziomoscon** [underscopeio/react-native-facebook-account-kit#29]
I have been happily using this library for two months now and does a great job. I have been using the client token flow where no backend is necessary.
As my app is getting more ready I would like to build a more secure authentication flow that involves exchanging client code for a server retrieved access_token. The official facebook doc pages:
https://developers.facebook.com/docs/accountkit/graphapi#at-validation
suggests to include the access_token in the header of each request so the backend can validate them using the graph API.
My question is whether this validation will add a bit of latency to each client requests. The alternative I was pondering is to generate a separate JTW token after the server authenticates the user so the backend can validate all subsequent calls simply checking the signature of the JWT and I would need to validate the user against facebook servers just the first time after login.

What would the community suggest?
How are you using this library?

Thanks

**Comment by gaguirre** [comment]
We are validating the user against graph api just once and then using JWT for subsequent requests, as you suggested.

Regarding **access token** vs **authorization code**, if you don't want access token to be passed through client side you should use the authorization code flow (see [this](https://developers.facebook.com/docs/accountkit/accesstokens?locale=en_US) for more info).

**Comment by mgorabbani** [comment]
Can anyone give me sample codes?
