### ISSUE TITLE
[iOS] AccountKit.getCurrentAccount() fails with Error: Could not get account data

### ISSUE THREAD

**Issue by tolu360** [underscopeio/react-native-facebook-account-kit#30]
Trying to get the logged-in account info with `AccountKit.getCurrentAccount()` fails with the error: `Could not get account data`, even though I can retrieve the current token with `AccountKit.getCurrentAccessToken()`. Please any ideas? I am doing ...
```js
AccountKit.getCurrentAccount()
        .then((account) => {
         ...
          })
})
```
On iOS.

Thanks

**Comment by tolu360** [comment]
[Update]


I think I was doing a few things wrong:
* I was not passing the `responseType` key in `RNAccountKit.configure({})` which you use in instantiating `_accountKit` (source: RNAccountKit.m)
* Noticed I was getting the error `API calls from the server require an appsecret_proof argument` in XCode console - I had to turn the app setting `Require App Secret` to `No` under the Account Kit dashboard.

Closing this... Thanks

**Comment by gaguirre** [comment]
Thanks @tolu360 for sharing this. Maybe we can improve the docs or something.
It does not work if `.configure()` is not called, right?

**Comment by tolu360** [comment]
You welcome @gaguirre. I think it should work, much later I noticed some defaults are being set by the package and `.configure()` is actually being called in the constructor - so calling `.configure()` serves to only overwrite the default config options. My issue was just as a result of the setting on Facebook App dashboard which I missed earlier.

As an aside passing the key `defaultCountry` in `.configure()` on android did not seem to work for me (it was still set as +1) and when I looked under the hood, `RNAccountKitModule.java` looks good to me. Any ideas?

**Comment by gaguirre** [comment]
Good to hear that! Regarding the `defaultCountry` issue you mentioned, let me try the sample and see if it's working for me.

**Comment by gaguirre** [comment]
Ok, this is really weird... It's like `US` it's overriding the default.
If you blacklist `US` then you will see the default country correctly. Try the following and let me know if it works for you too.
```
AccountKit.configure({
  countryBlacklist: ["US"],
  defaultCountry: "AR",
})
```

**Comment by tolu360** [comment]
Weird... blacklisting `US` does make my `defaultCountry` work correctly. Why do you think it works though?

**Comment by gaguirre** [comment]
Probably an issue on the Android SDK.
What about iOS? same issue? I'm reporting this bug on developers.facebook.com/bugs page.
Follow this in #31

**Comment by tolu360** [comment]
Funnily and odd enough, setting the `defaultCountry` works just fine on iOS. Great work on this package, by the way!
