### ISSUE TITLE
Resend code is always white on Android

### ISSUE THREAD

**Issue by zevmo** [underscopeio/react-native-facebook-account-kit#32]
The 'Resend code' link is always white on Android. Is there a way to change this?

**Comment by gaguirre** [comment]
Hi @zevmo, did you try changing the theme? If not, see [this doc section](https://github.com/underscopeio/react-native-facebook-account-kit#android).

**Comment by zevmo** [comment]
Hi @gaguirre, yeah, we have this configured, but it seems that none of the options changes that one.

**Comment by gaguirre** [comment]
Oh... probably an issue with the Android SDK.
Could you take a screenshot? So we can submit an issue to http://developers.facebook.com/bugs

Thanks!

**Comment by zevmo** [comment]
![screen shot 2016-08-18 at 9 12 54 am 1](https://cloud.githubusercontent.com/assets/2286035/17778830/6a93f2de-6533-11e6-819c-b6500c58f93e.png)

**Comment by gaguirre** [comment]
Good news @zevmo! This issue was fixed in the new Android SDK release :)

![resend-code-fixed](https://cloud.githubusercontent.com/assets/1652196/18168665/2c412b6e-702d-11e6-8605-ad6acacbd001.png)

**Comment by zevmo** [comment]
@gaguirre do you know which prop it uses?

**Comment by gaguirre** [comment]
It's the one defined as `com_accounkit_primary_color` in the [styles.xml](https://github.com/underscopeio/react-native-facebook-account-kit/blob/master/sample/android/app/src/main/res/values/styles.xml#L9) file.

Notice that's used for `com_accountkit_input_accent_color ` and `com_accountkit_input_border_color ` properties too.
