### ISSUE TITLE
Switch component stop responding on Android

### ISSUE THREAD

**Issue by artkow** [underscopeio/react-native-facebook-account-kit#35]
After pressing on Switch and move finger outside component area before releasing it the component stops working.

When I remove package react-native-facebook-account-kit and use basic react-native then Switch works all the time good.

This happens on example witch patch:

```
diff --git a/sample/app.js b/sample/app.js
index 49b6230..b9ba0b9 100644
--- a/sample/app.js
+++ b/sample/app.js
@@ -19,7 +19,8 @@ import AccountKit, {
 class AccountKitSample extends Component {
   state = {
     authToken: null,
-    loggedAccount: null
+    loggedAccount: null,
+    val: false
   }

   componentWillMount() {
@@ -130,7 +131,7 @@ class AccountKitSample extends Component {
           onLogin={(token) => this.onLogin(token)} onError={(e) => this.onLogin(e)}>
           <Text style={styles.buttonText}>SMS</Text>
         </LoginButton>
-
+        <Switch onValueChange={(value) => this.setState({val: value})} value={this.state.val} />
         <TouchableOpacity style={styles.button} onPress={() => this.onEmailLoginPressed()}>
           <Text style={styles.buttonText}>Email</Text>
         </TouchableOpacity>
```

workaround:
use in Switch function:
onResponderRelease={()=> this.setState({val: !this.state.val })}

**Comment by gaguirre** [comment]
Hi @artkow, what do you mean with _the component stops working_?
Could you post a screenshot or gif maybe? I can't reproduce it in the emulator.

**Comment by artkow** [comment]
Hi,
I forgot mention that this happens on android devices (no emulator). I use phone with Android ver 5.0.1 and 4.4.2.
I've done test on ios emulator and it works good too.

**Comment by gaguirre** [comment]
Sorry for the delay @artkow 
I could reproduce it but don't know why it happens. I also tried removing all `react-native-facebook-account-kit` stuff but still fails, so it may be a React Native issue.

**Comment by aschenkel** [comment]
Closing this one due to inactivity
