### ISSUE TITLE
Bump version for AK SDKs 4.15+

### ISSUE THREAD

**Issue by zevmo** [underscopeio/react-native-facebook-account-kit#37]
Update to the latest SDK versions for Account Kit.

**Comment by gaguirre** [comment]
Hi @zevmo, i just checked the version [is set to 4.+](https://github.com/underscopeio/react-native-facebook-account-kit/blob/master/android/build.gradle#L23) so it should get the 4.15+ version when building the project.

I'll try running the sample now and see if some pending issues were fixed. Thanks!

**Comment by tmjordan** [comment]
Hi, first thank you for that amazing project. It really helps.
But can u please upgrade to the latest SDK, currently it is 4.39
I've found a workaround on ios by downloading the sdk myself but i don't find any solution on android.
Thanks!!
