### ISSUE TITLE
RNAccountKitNative.configure is not an object

### ISSUE THREAD

**Issue by arhmnsh** [underscopeio/react-native-facebook-account-kit#38]
I'm getting below error when trying to run on Android. Works fine on iOS.

![image](https://cloud.githubusercontent.com/assets/1363724/18223962/9ebf97c2-71cf-11e6-8e35-cf5e1c1e3872.png)

**Comment by GeoffreyPlitt** [comment]
@arhmnsh  What was the solution? We're seeing the same error, in our Mocha tests.

**Comment by gaguirre** [comment]
Hi @GeoffreyPlitt, make sure you've re-built the _native project_ running `react-native run-ios`/`react-native run-android` so that native changes will be reflected.
And please submit a new issue instead of reply on three different issues! 😃

**Comment by GeoffreyPlitt** [comment]
Runs fine in all simulators and devices. The only place it breaks is our Mocha tests, because the module wasn't transpiled (i.e. Babel) like other modules, from what I can tell.

**Comment by gaguirre** [comment]
Are you having this issue for Android, iOS or both platforms?

**Comment by GeoffreyPlitt** [comment]
This doesn't involve _either_ Android or iOS. We're using the framework from https://github.com/futurice/pepperoni-app-kit#testing-setup, and https://github.com/lelandrichardson/react-native-mock so that the Mocha tests can run on the RN codebase without actually touching Android/iOS stuff.

**Comment by GeoffreyPlitt** [comment]
I'm going to move forward with this issue in https://github.com/underscopeio/react-native-facebook-account-kit/issues/48, let's do further comments there-- thanks for your help so far.
