### ISSUE TITLE
AccountKit.logout() success function doesn't get called

### ISSUE THREAD

**Issue by arhmnsh** [underscopeio/react-native-facebook-account-kit#39]
Whenever AccountKit.logout() is called, the code inside the success promise doesn't get executed.
Tried it my own app as well as the sample app in this repo.

**Comment by gaguirre** [comment]
Hi @arhmnsh, this is for iOS, Android or both?

**Comment by gaguirre** [comment]
We'll try to fix #40 and release a new version with both fixes in these days.
@arhmnsh if you need this immediately you can install it from master.
