### ISSUE TITLE
Login details are not persisted

### ISSUE THREAD

**Issue by arhmnsh** [underscopeio/react-native-facebook-account-kit#40]
AccountKit.getCurrentAccount() doesn't return user details  once the app has been closed.

**Comment by gaguirre** [comment]
@arhmnsh could you post the repro steps?

I did the following in iOS and it worked

1. Login with email
2. See the **Logout** button and the account info
3. Close and open the app again, wait one second and see the account info

**Comment by arhmnsh** [comment]
@gaguirre I tried that with SMS. Doesn't work.

1. Login with email
2. See the Logout button and the account info
3. Close and open the app again, see the Login button

Right now, I've solved it by saving logindetails on AsyncStorage. So, when the app starts cold, I look for logindetails in AsyncStorage, if not present, show the login button.

**Comment by gaguirre** [comment]
Ok, I'll try with SMS. It may be an Account Kit SDK's issue, because it works with the email.
Do you know if this happen with Android too?

**Comment by gaguirre** [comment]
I can't reproduce the error neither with SMS nor email.
<img width="150" alt="screen shot 2016-09-09 at 10 48 19 am" src="https://cloud.githubusercontent.com/assets/1652196/18389474/7c388400-767c-11e6-8a55-582dcef8f744.png">

**Comment by gaguirre** [comment]
@arhmnsh did you try again with the new version?

**Comment by arhmnsh** [comment]
@gaguirre I tried it on Android and it works fine now. Thanks mate! :)

**Comment by gaguirre** [comment]
You're welcome @arhmnsh!
