### ISSUE TITLE
Does not work with latest RN versions

### ISSUE THREAD

**Issue by rogerkerse** [underscopeio/react-native-facebook-account-kit#41]
Error:(32, 8) error: RNAccountKitModule is not abstract and does not override abstract method onActivityResult(Activity,int,int,Intent) in ActivityEventListener

Simple gradle sync fails in android studio because of this error.

**Comment by GeoffreyPlitt** [comment]
What was the solution?

**Comment by rogerkerse** [comment]
https://github.com/underscopeio/react-native-facebook-account-kit/pull/42
