### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by zevmo** [underscopeio/react-native-facebook-account-kit#43]
Is there anything, in particular, we need to do in order to have AK able to be capable of language support? When changing the country, I would have assumed the rest of the interface and texts will be adjusted to the language for that country.

**Comment by gaguirre** [comment]
@zevmo what do you want from the following?
- The _AK screen_ language should change based on a configuration value
- The _AK screen_ language should change when the user selects a country for the SMS
- Your app's language should change when the user selects a country for the SMS

It seems Account Kit does not support language configuration in runtime. It uses the user's phone language. See the [official docs](https://developers.facebook.com/docs/accountkit) for more info.

**Comment by zevmo** [comment]
@gaguirre International phones with Polish or Spanish only see english in the current implementation. Is there something that needs to be done for it to look at the phone's language? Official docs were extremely vague with this.

**Comment by gaguirre** [comment]
@zevmo I tried the example for RN 0.33 on Android and it's working (see the image with **Spanish** as language below).
The issue you mention is only for iOS, right?

<img width="410" alt="screen shot 2016-09-19 at 3 39 03 pm" src="https://cloud.githubusercontent.com/assets/1652196/18644562/43df7db4-7e80-11e6-8d4e-a65beb3f89d2.png">

**Comment by zevmo** [comment]
@gaguirre iOS, correct. Android works

**Comment by gaguirre** [comment]
@zevmo ok, thanks! I'll upgrade to the latest iOS SDK version and see what happens.

**Comment by gaguirre** [comment]
@zevmo see the related commit.
It was related to the `CFBundleDevelopmentRegion` configuration value, just need to be unset.
