### ISSUE TITLE
Error:(33, 8) error: RNAccountKitModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener

### ISSUE THREAD

**Issue by shyjal** [underscopeio/react-native-facebook-account-kit#44]
Works great on iOS, but after following Android setup guide the gradle build fails. I'm getting this error:

Error:(33, 8) error: RNAccountKitModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener

Probably a React native  v0.33 specific bug

**Comment by gaguirre** [comment]
Hi @shyjal, are you using the latest version?
We published the **0.5.0** yesterday and should be compatible with **RN 0.33**.

**Comment by gaguirre** [comment]
I'll close this issue that should be fixed in **0.5.0** release. Please reopen if not.
