### ISSUE TITLE
Login View shows under everything else?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [underscopeio/react-native-facebook-account-kit#46]
When we do loginWithPhone(), the views it shows are being placed UNDER our AppView and navigation views.

How to show them above?

**Comment by gaguirre** [comment]
I didn't hear about this before. Could you take a screenshot?
Also, would you try with the example app to see if this issue is specific to your project?

**Comment by aschenkel** [comment]
Closing it due to inactivity
