### ISSUE TITLE
Error layout when choose country

### ISSUE THREAD

**Issue by 2ducanhpham** [underscopeio/react-native-facebook-account-kit#49]
screen shot
![simulator screen shot oct 3 2016 5 15 08 pm](https://cloud.githubusercontent.com/assets/14899775/19034387/519c176a-898d-11e6-9e2f-2da19e7e947d.png)

**Comment by gaguirre** [comment]
Weird! Which version of this module are you using?
Do you have repro steps for this issue?

**Comment by 2ducanhpham** [comment]
My package.json 
"dependencies": {
    "react": "15.3.2",
    "react-native": "^0.34.1",
    "react-native-facebook-account-kit": "^0.5.1",
...
@gaguirre

**Comment by gaguirre** [comment]
Thanks @2ducanhpham. 
Did you face this with previous versions of React Native?

**Comment by 2ducanhpham** [comment]
only error with React Native 0.34

**Comment by sham3k** [comment]
+1

**Comment by gaguirre** [comment]
It seems to be working in the last React Native version. Please, reopen if it persists after upgrading RN.

**Comment by nopmengkoung** [comment]
I got this error on iOS too.
My package.json
"react": "~15.4.1",
"react-native": "0.42.0",
"react-native-facebook-account-kit": "^0.6.2",

**Comment by aidinb** [comment]
me too

**Comment by gaguirre** [comment]
@nopmengkoung @aidinb which version (exactly) of `react-native-facebook-account-kit` and `react-native`?

**Comment by aidinb** [comment]
"react-native": "0.48.2",
