### ISSUE TITLE
rnpm install the module before linking

### ISSUE THREAD

**Issue by fabriziomoscon** [underscopeio/react-native-facebook-account-kit#5]
I am new to rnpm but I think contrary to what suggested in the `README.md` you need

```
   rnpm install react-native-facebook-account-kit
   rnpm link react-native-facebook-account-kit
```

Let me know if that makes sense?

**Comment by gaguirre** [comment]
@fabriziomoscon you're right, thanks! I'll change it right now.
`rnpm install react-native-facebook-account-kit` should be enough since it will install _and_ link the lib, as mentioned in [rnpm docs](https://github.com/rnpm/rnpm#running)
