### ISSUE TITLE
Module not being registered

### ISSUE THREAD

**Issue by pnakibar** [underscopeio/react-native-facebook-account-kit#54]
### Issue Description
I'm getting "Cannot read property 'login' of undefined", further down investigating the problem, I see that it's not being registered as a Native Module.

### Steps to Reproduce / Code Snippets
1. react-native init accountkittests
2. npm install --save react-native-facebook-account-kit
3. react-native link react-native-facebook-account-kit
4. fill the ids and keys
5. react-native run-android
6. npm start

When I check if the native module is linked I get a undefined:

```javascript
const RNAccountKitNative = NativeModules.RNAccountKit // evaluates undefined
console.log(NativeModules) // nothing related to it
```

#### Expected Results
To run the account kit popup.

### Additional Information

* React Native Account Kit version: 0.5.2 (from both npm and github)
* React Native version: 0.3.7
* Platform(s) (iOS, Android, or both?): Android (don't know about ios)

**Comment by gaguirre** [comment]
Hi @pnakibar, could you please post a snippet of how you're using this module?

**Comment by gaguirre** [comment]
Hi @pnakibar, please check that in your `MainApplication.java` you have the `RNAccountKitPackage` registered

```java
@Override
protected List<ReactPackage> getPackages() {
  return Arrays.<ReactPackage>asList(
    new MainReactPackage(),
    new RNAccountKitPackage()  // <-- this line
  );
}
```

**Comment by sinn1** [comment]
Had this problem with iOS (worked ok with Android). Not sure what caused the problem but I deleted my ios/build folder and ran react-native run-ios again. Worked fine after that.
