### ISSUE TITLE
Not able to use backgroundImage

### ISSUE THREAD

**Issue by srijan02420** [underscopeio/react-native-facebook-account-kit#55]
### Issue Description

I am not able to use backgroundImage in theme. Please tell me what path to give or where should I put my account_kit_back.jpg.

### Steps to Reproduce / Code Snippets

```javascript
RNAccountKit.configure({
      titleType: 'title',
      theme: {
        // Background
        // backgroundColor: Color.hex(Colors.SILVER_GREY),
        backgroundImage: 'account_kit_back.jpg',
        // Button
        buttonBackgroundColor: Color.hex(Colors.WHITE),
        buttonBorderColor: Color.hex(Colors.WHITE),
        buttonTextColor: Color.hex(Colors.PRIMARY_GREY),
        // Button disabled
        buttonDisabledBackgroundColor: Color.rgba(255, 255, 255, 0.5),
        // Header
        headerBackgroundColor: Color.hex(Colors.ECHO_GREEN),
        headerButtonTextColor: Color.hex(Colors.PRIMARY_GREY),
        headerTextColor:Color.hex( Colors.PRIMARY_GREY),
        // Input
        inputBackgroundColor: Color.rgba(255, 255, 255, 0.5),
        inputBorderColor: Color.hex(Colors.WHITE),
        inputTextColor: Color.hex(Colors.PRIMARY_GREY),
        // Others
        iconColor: Color.hex(Colors.ECHO_GREEN),
        textColor: Color.hex(Colors.PRIMARY_GREY),
        titleColor: Color.hex(Colors.PRIMARY_GREY),
        // Header
        statusBarStyle: StatusBarStyle.LightContent, // or StatusBarStyle.Default
      }
    })
```

#### Expected Results

Image should come as background.

**Comment by gaguirre** [comment]
Hi @srijan02420, which platform are you targeting? Android, iOS or both?

**Comment by gaguirre** [comment]
For **iOS** you must add the image to the Xcode project Assets doing the following:
1. Open your project on Xcode
1. Go to your project folder and then to `Image.xcassets`
1. In the middle section do a right click and then _New image Set_

<img width="1014" alt="screen shot 2016-12-17 at 2 38 07 pm" src="https://cloud.githubusercontent.com/assets/1652196/21288734/4a939256-c469-11e6-8c19-7dc719ba2eaa.png">

Then drag and drop the image you want and rename it (e.g _backgroundAK_)

<img width="752" alt="screen shot 2016-12-17 at 2 58 58 pm" src="https://cloud.githubusercontent.com/assets/1652196/21288748/83d5c426-c469-11e6-90b5-5eeb261e3af2.png">

Finally, in your code you need to set the `background` property with the Image Set name (in this case `backgroundAK`).

```javascript
RNAccountKit.configure({
  titleType: 'title',
    theme: {
      backgroundColor: 'rgba(0,0,0, 0.4)',
      backgroundImage: 'account_kit_back.jpg',
      ...
    }
  }
})
```

> IMPORTANT: use a background color with opacity less than 1, otherwise it will cover the image

And this is how it looks in your app
![screen shot 2016-12-17 at 3 04 53 pm](https://cloud.githubusercontent.com/assets/1652196/21288763/2e55e19c-c46a-11e6-84de-b79173280e4f.png)

**Comment by gaguirre** [comment]
For **Android** you need to put the image in the `android/app/src/main/res/drawable` folder (create if not exists).

Then [create a theme](https://github.com/underscopeio/react-native-facebook-account-kit#android) with the `com_accountkit_background` property set to the image name withouth the extension (i.e. if the image file is `bicycle.jpg`, the property will be `bicycle`).

For a working example for both platforms, check the [RN039 example](https://github.com/underscopeio/react-native-facebook-account-kit/tree/master/examples/RN039)

**Comment by srijan02420** [comment]
backgroundColor: 'rgba(0,0,0, 0.4)' was the issue. Its compulsory to add a non-opaque background. Thanks. Working fine.

**Comment by gaguirre** [comment]
Great! Good to hear that @srijan02420!

**Comment by anbu369** [comment]
@gaguirre Hi, I tried to run RN039 example and get the following error? can you please help?

Error retrieving parent for item: No resource found that matches the given name 'Theme.AccountKit.Outline'.
