### ISSUE TITLE
react native link facebook account kit not working for android

### ISSUE THREAD

**Issue by baguspazpo** [underscopeio/react-native-facebook-account-kit#56]
when I running react-native link react-native-facebook-account-kit more than 1 time,, the result is
* for android always -> has been successfully installed
* for ios -> already linked

then in file MainApplication.Java the result
```java
import io.underscope.react.fbak.RNAccountKitPackage;
import io.underscope.react.fbak.RNAccountKitPackage;
import io.underscope.react.fbak.RNAccountKitPackage;

protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new RNAccountKitPackage(),
            new RNAccountKitPackage(),
            new RNAccountKitPackage(),
            new ImagePickerPackage(),
            new VectorIconsPackage()
      );
    }
```
Then in the file setting.gradle and build.gradle, both of the file don't change....

so.. while i run react-native run-android... i have error

can you help me.....

**Comment by gaguirre** [comment]
Hi @baguspazpo. You should run `react-native link` just once.

However, to _repair_ your current state you can remove the repeated lines and your file will look like
```java
import io.underscope.react.fbak.RNAccountKitPackage;

protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new RNAccountKitPackage(),
            new ImagePickerPackage(),
            new VectorIconsPackage()
      );
    }
```

Tell me if that works for you!
