### ISSUE TITLE
Poorly formatted country code crashes app

### ISSUE THREAD

**Issue by Andreyco** [underscopeio/react-native-facebook-account-kit#57]
### Issue Description

Poorly formatted country code (e.g. lowercased) crashed the app.

### Steps to Reproduce / Code Snippets

Given `countryWhitelist: ['us', 'sk']`, app crashes (feel free to use any country code)

#### Expected Results

App should not crash.

### Additional Information

* React Native Account Kit version: 0.5.2
* React Native version: 0.39
* Platform(s): Android (not sure about iOS)
* `defaultCountry: 'sk',` works as expected. Lowercased country code is not problem here.

**Comment by gaguirre** [comment]
Good catch @Andreyco! I guess we can solve this issue easily mapping the `countryWhitelist` and applying `toUpperCase` to each item.

Would you like to send a PR? I'll fix it this week otherwise.

**Comment by Andreyco** [comment]
@gaguirre sure, will add some error reporting as well, currently I have no clue, whether I use correct country code, or not...

Do you approve doing all check in Javascript codebase?

**Comment by gaguirre** [comment]
Yes, that's what I meant. It would be better since will affect both platforms ;)
