### ISSUE TITLE
Missing instruction to initialise sdk

### ISSUE THREAD

**Issue by fabriziomoscon** [underscopeio/react-native-facebook-account-kit#6]
In the `README.md` is missing any reference to Native SDK initialisations.

For everyone interested in Android, you need to add the app id and app name to the `AndroidManifest.xml`
Follow these instructions: https://developers.facebook.com/docs/accountkit/android#initsdk

I am not sure for iOS

**Comment by gaguirre** [comment]
Thanks again @fabriziomoscon :)
Take a look at the docs now, any feedback is welcome.
