### ISSUE TITLE
Is there a alternative to hide legal text for Android?

### ISSUE THREAD

**Issue by mauriciocoelho** [underscopeio/react-native-facebook-account-kit#66]
For iPhone there is a `textColor` and it's possible add a transparent color to hide legal text, but in Android there is a `com_accountkit_secondary_text_color` for all texts, not only to legal text :(

**Comment by gaguirre** [comment]
@mauriciocoelho what you're doing seems like a hack! 😃 
I'd check the terms and conditions before hiding the legal texts...

**Comment by mauriciocoelho** [comment]
Only for knowledge 😂
