### ISSUE TITLE
Seems like not compatible with Android 4.4

### ISSUE THREAD

**Issue by Dimasik911** [underscopeio/react-native-facebook-account-kit#67]
## Hey there! Please follow the steps described below

Before submit a new issue be sure about the following points

- [x] You're using the latest release of this module: https://github.com/underscopeio/react-native-facebook-account-kit/releases

- [x] You've searched through existing issues: https://github.com/underscopeio/react-native-facebook-account-kit/issues and the issue is not already reported.

- [x] You have filled out the template below, or provided an equivalent amount of detail.

Describe your issue in as much detail as possible. Provide **screenshots** where appropriate. Provide a **minimal code snippet** or include a list of detailed list of steps that reproduce the issue.

--- delete everything above this line before submitting your issue ---

### Issue Description

I'm using accountKit for one project and it works fine with IOS >= 9.3 devices and Android  >= 5.0 but crashes on Android 4.4. Searched through different sources but could  not find any answer to this issue. Is it compatible with Android 4.4?
[FILL THIS OUT]

### Steps to Reproduce / Code Snippets

[FILL THIS OUT]

#### Expected Results

[FILL THIS OUT]

### Additional Information

* React Native Account Kit version: [FILL THIS OUT]
* React Native version: [FILL THIS OUT]
* Platform(s) (iOS, Android, or both?): [FILL THIS OUT]

**Comment by Dimasik911** [comment]
@RossKinsella, there was something about android drawables. You need to check error in Android Studio.

**Comment by RossKinsella** [comment]
Oh... I was under the impression it was something quite different. https://github.com/underscopeio/react-native-facebook-account-kit/issues/121
