### ISSUE TITLE
A system issue occured

### ISSUE THREAD

**Issue by anbublacky** [underscopeio/react-native-facebook-account-kit#68]
I'm using the latest version 0.40, I have searched existing issues, also googled could not find the error
I followed the guidelines mentioned in this package, i'm able to get the login interface for mobile when i give next after mobile number gets prefilled, i'm getting the following error.

"A system issue occured, Please try again"

**Comment by nikolay-radkov** [comment]
I am also having this error on react-native 0.41.2

**Comment by gaguirre** [comment]
Ok, do you have any extra info (logs, screenshots) that could help to fix it?
Thanks for reporting this issue!

**Comment by nikolay-radkov** [comment]
The problem is occuring if I am disabled the client access token flow in account kit dashboard. By their documentation it should work and tge response should contain short-lived access token. Instead it show the error above. Adb logcat is not showing anything.

**Comment by anbublacky** [comment]
It is working when i change require App secret to no in developer dashboard

**Comment by pyankoff** [comment]
Tried "Require App Secret" to NO, still getting the same error

**Comment by dp-singh** [comment]
I man using it in android, followed everything mentioned in the repo. After filling the phone number, it always shows System error occurred that to without any logs.
![screenshot_1492342867](https://cloud.githubusercontent.com/assets/2740228/25070910/d4b8b09e-22c7-11e7-82e5-dfbbeb3c610d.png)

**Comment by gaguirre** [comment]
@dp-singh the integration seems to be ok, since the view you're seeing is provided by the Account Kit SDK. Apparently it's an internal issue, probably retrieved by the Account Kit _service_.
Could you see the Android logs?

**Comment by nikolay-radkov** [comment]
@dp-singh I have the same problem and it was because **YES** was set in **Enable the client access token flow** in account kit dashboard, but in the library configurations, **responseType** was the default one - **token**. It should be set to **code** if you want to get the authorization code on the client. 

`// Configures the SDK with some options`
`RNAccountKit.configure({`
`  responseType: 'token'|'code' // 'token' by default,` **<------------- THIS SHOULD BE - _code_**
`....`
`})`

**Comment by gaguirre** [comment]
Thanks @nikolay-radkov! It's something could be added to the documentation?
A PR would be great ;)

**Comment by jslz** [comment]
hi, (thanks for this library!) for me it works on iOS but not on Android, I am facing the same situation - the fix by @nikolay-radkov doesn't yet seem to work for me. I will keep seeing if I can figure out anything, but would appreciate hearing from anybody else on Android.

**Comment by jayprakash1** [comment]
@jslz I was facing this issue as well. I made a mistake of using AccountKit app secret as ak_client_token. Perhaps check that once to be sure.

**Comment by rodnolan** [comment]
I'm on Android, react-native@0.48.4 and react-native-facebook-account-kit@0.8.0. Just dropping a quick note here to help anyone who may have made the same dumb mistake that I made.

I solved my "A system issue occurred" problem by defining the _correct_ value for my Account Kit Client Token in strings.xml.

**Comment by prodhan** [comment]
I am using php. same problem. What can I do now?

**Comment by jitenbansal** [comment]
In AccountKit dashboard  find "Enable Client Access Token Flow" and set it ON.
It worked for me.

**Comment by anuragprajapat** [comment]
Add Product-> Account Kit-> Advanced Settings -> Configure Keys

**Comment by rassemdev** [comment]
Thanks @nikolay-radkov  your solution solved the problem.. Saved my day

**Comment by amanix007** [comment]
Thanks @nikolay-radkov

**Comment by tbanj** [comment]
Thanks @nikolay-radkov your solution works and after i changed it back to the .TOKEN it still work though at first initialization it have to be set to .CODE

**Comment by gHashTag** [comment]
I forgot to publish the application. After switching everything worked.

<img width="312" alt="screenshot 2019-02-02 at 22 41 07" src="https://user-images.githubusercontent.com/6774813/52168466-c0a36c00-273b-11e9-9a8c-8f0c81101d76.png">

**Comment by jose920405** [comment]
@gHashTag 

Do you think that is really necessary publish the app. I think that in dev mode should works. Can someone confirm?

**Comment by jose920405** [comment]
I did try to publish and the errors still appearing

**Comment by prabhat04011998** [comment]
Account kit is deprecated due to which it's showing "A system issue occurred. Please try again."..

M i right or anything else? 
![image](https://user-images.githubusercontent.com/28345582/78498787-ff7ee880-7769-11ea-9f36-9a3d4d45fdf2.png)
