### ISSUE TITLE
Prefill Phone Number

### ISSUE THREAD

**Issue by zachrnolan** [underscopeio/react-native-facebook-account-kit#69]
Is it possible to prefill the phone number? I know Account Kit itself allows this, but I'm not seeing anything for it in this libraries configuration.

Thanks!

**Comment by gaguirre** [comment]
You're right @zachrnolan 
Excellent opportunity to send a PR!! 😃  It should be very similar to how `initialEmail` works (see [Usage](https://github.com/underscopeio/react-native-facebook-account-kit#usage) section).

I'll do it later if not, don't worry.

**Comment by gaguirre** [comment]
This feature is included in version [**0.7.0**](https://github.com/underscopeio/react-native-facebook-account-kit/releases/tag/v0.7.0) @zachrnolan

**Comment by zachrnolan** [comment]
Thanks @gaguirre!
