### ISSUE TITLE
Order of config options is wrong.

### ISSUE THREAD

**Issue by smshuja** [underscopeio/react-native-facebook-account-kit#7]
The order of config options seems to be wrong.

https://github.com/underscopeio/react-native-facebook-account-kit/blob/70e956258507f21bd327562c53cc6a5547e58ecd/index.js#L22

```javascript
const configOptions = {
    ...options,
    ...RNAccountKit.configDefaults
}
```
should be
```javascript
const configOptions = {
    ...RNAccountKit.configDefaults,
    ...options
}
```

**Comment by gaguirre** [comment]
You're right 👍
Will be fixed in seconds, thanks!

**Comment by smshuja** [comment]
Thanks @gaguirre 
I have added theme options to customize the colors and background image.

https://github.com/smshuja/react-native-facebook-account-kit/commit/774f757122771445bfbf79b48198c7a3fb0796c8

Should I send a pull request?

**Comment by gaguirre** [comment]
@smshuja sure!
