### ISSUE TITLE
ios: country list seems unconfigured

### ISSUE THREAD

**Issue by fabriziomoscon** [underscopeio/react-native-facebook-account-kit#74]
* React Native Account Kit version: 0.6.2
* React Native version: 0.43.4
* Platform(s) (iOS, Android, or both?): iOS

Providing this configuration:

```javascript
{
        responseType: 'code',
        titleType: 'login',
        initialAuthState: '',
        // facebookNotificationsEnabled: true|false, // true by default
        facebookNotificationsEnabled: true,
        // readPhoneStateEnabled: true|false, // true by default,
        readPhoneStateEnabled: true,
        // receiveSMS: true|false, // true by default,
        receiveSMS: true,
        // countryWhitelist: ['AR'], // [] by default
        // countryBlacklist: ['US'], // [] by default
        defaultCountry: 'GB',
        theme: {
            backgroundColor:               Color.hex(colors.mainBackground),
            buttonBackgroundColor:         Color.hex(colors.active),
            buttonBorderColor:             Color.hex(colors.active),
            buttonTextColor:               Color.hex(colors.white),
            buttonDisabledBackgroundColor: Color.hex(colors.lightGray),
            buttonDisabledBorderColor:     Color.hex(colors.lightGray),
            buttonDisabledTextColor:       Color.hex(colors.darkerGray),
            headerBackgroundColor:         Color.hex(colors.appBar),
            headerTextColor:               Color.hex(colors.white),
            headerButtonTextColor:         Color.hex(colors.white),
            iconColor:                     Color.hex(colors.active),
            inputBackgroundColor:          Color.hex(colors.white),
            inputBorderColor:              Color.hex(colors.appBar),
            inputTextColor:                Color.hex(colors.appBar),
            textColor:                     Color.hex(colors.darkerGray),
            titleColor:                    Color.hex(colors.darkerGray),
            // backgroundImage: 'background.png',
            // statusBarStyle: StatusBarStyle.LightContent, // or StatusBarStyle.Default
        }
    }
```

I can see a country list where all country codes are replaced by keys

<img width="376" alt="screen shot 2017-05-15 at 20 06 01" src="https://cloud.githubusercontent.com/assets/721890/26074633/6a34c13c-39aa-11e7-8412-4fe4aee1c610.png">

<img width="375" alt="screen shot 2017-05-15 at 20 05 51" src="https://cloud.githubusercontent.com/assets/721890/26074644/704c21e6-39aa-11e7-9e7a-03f9efe82a5e.png">

On Android everything works fine

**Comment by gaguirre** [comment]
Hi @fabriziomoscon, this issue is probably related to _bad linked_ dependencies from the **AccountKit.framework**.
Could you please check you've _drag&dropped_ the **AccountKitStrings.bundle** to your project in Xcode?

**Comment by fabriziomoscon** [comment]
I am struggling to set up the ios library, following the README.
I got this

![screen shot 2017-05-15 at 20 26 36](https://cloud.githubusercontent.com/assets/721890/26075365/e7188e0c-39ac-11e7-8c91-6dc6bad300f4.png)

**Comment by fabriziomoscon** [comment]
@gaguirre I am relatively new to ios and xcode, I am using xcode 8.3 and I open my project workspace because of cocoa pods.
I tried to unlink the library and then link it again. Dragging the frameworks as explained in the readme sometimes returns an error popup saying that there is already a file with that name.

I have not made any progress on this. I would really appreciate your input.

**Comment by gaguirre** [comment]
@fabriziomoscon Xcode is a real shi#
My advice is to use git (`git diff`) to see what changes Xcode does in your project while you're adding a framework or anything.
Try removing the framework (see there is nothing related to it in your `ios` folder) and start again. 😑

**Comment by fabriziomoscon** [comment]
Yes, Thank you!
I am doing this process as you describe every time.

I will post when I will find a solution

**Comment by fabriziomoscon** [comment]
I found a warning in my compiler which I think is related:
`warning: skipping file '/Users/fab/projects/hoxfon/client/node_modules/react-native-facebook-account-kit/ios/AccountKitStrings.bundle' (unexpected file type 'wrapper.plug-in' in Frameworks & Libraries build phase)`

**Comment by fabriziomoscon** [comment]
All fixed now!
Steps to fix it:
- `react-native unlink react-native-facebook-account-kit`
- open your `project.pbxproj` file and remove manually anything with AccountKet* or similar
- remove the imported Facebook Frameworks from the `ios` directory (note that this files where present on the project but not shown on xcode)
- `react-native link react-native-facebook-account-kit`
- drag Facebook frameworks into the project

**Comment by gaguirre** [comment]
Glad to hear that!

**Comment by danhnguyeen** [comment]
this issue have appeared again in RN 0.59.8. How can I fix it please?
