### ISSUE TITLE
iOS: E-mail login cancelled no error thrown

### ISSUE THREAD

**Issue by ekeuus** [underscopeio/react-native-facebook-account-kit#76]
### Issue Description

AccountKit email login cancel error is not being thrown for iOS. Works as expected for Android.

### Steps to Reproduce / Code Snippets

When a user tries to login with email, but decides do not do so, no error is being thrown for iOS. "loginWithEmail 1" is printed but nothing else happens.

`
console.log('loginWithEmail 1')
const result = await RNAccountKit.loginWithEmail()
console.log('loginWithEmail 2')
`

#### Expected Results

Throw error or return no token. 

### Additional Information

* React Native Account Kit version: 0.6.2
* React Native version: 0.44.0
* Platform(s) (iOS, Android, or both?): iOS

**Comment by thienpow** [comment]
same to sms login

**Comment by jpgarcia** [comment]
Closing this. Should be fixed on `v1.1.0` as described here https://github.com/underscopeio/react-native-facebook-account-kit/pull/164
