### ISSUE TITLE
Question: how to generate test accounts for fb acc kit?

### ISSUE THREAD

**Issue by fabriziomoscon** [underscopeio/react-native-facebook-account-kit#77]
I ma using SMS only login and my ios app got rejected by Apple, because they were not able to login. I believe they tried during a day when SMS from Facebook were delayed or not sent at all, because I experienced similar issues on the same weekend.

Apple reviewers asked for a static SMS code to bypass the verification. I am not aware of a similar thing, and I can't find anything neither on the official documentation nor researching on the Internet.

Has anybody had Apple review issue for this and could you share how you fixed it?

**Comment by davidpaulsson** [comment]
Yes, this would be very helpful! Anyone? 💯

**Comment by jpgarcia** [comment]
Closing this as it's not a library issue. I'd rather post this on https://www.facebook.com/help/community/
