### ISSUE TITLE
Failed to receive SMS code, how to use the phonecall workaround?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [underscopeio/react-native-facebook-account-kit#78]
I've encountered an iPhone (AT&T carrier) which never receives the SMS code, and I've verified that a bunch of other apps (which use internet and SMS) work, and it can receive SMS messages from my phone, and there aren't any blacklists or anything.

According to https://developers.facebook.com/docs/accountkit/overview, there's a workaround where the user gets a phonecall with the code.

Does this library provide that? I don't see anything here about that.

**Comment by GeoffreyPlitt** [comment]
@tszajna0 @Andreyco @jpgarcia @ignacioola @Vrtak-CZ @vcalvello  @smshuja  Any ideas?

**Comment by thienpow** [comment]
my problem is, the phone number has been activated to use facebook code... so the sms is disabled and i don't know how to disable facebook code and get back to use sms only.

**Comment by jpgarcia** [comment]
Closing this as the latest version allows you to validate your phone using phonecall or facebook notification. See https://github.com/underscopeio/react-native-facebook-account-kit/pull/171#issuecomment-453938630
