### ISSUE TITLE
No resource found error

### ISSUE THREAD

**Issue by MuruganSKutty** [underscopeio/react-native-facebook-account-kit#80]
Building and installing the app on the device (cd android && ./gradlew installDebug)...
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:react-native-facebook-account-kit:preBuild UP-TO-DATE
:react-native-facebook-account-kit:preReleaseBuild UP-TO-DATE
:react-native-facebook-account-kit:checkReleaseManifest
:react-native-facebook-account-kit:preDebugAndroidTestBuild UP-TO-DATE
:react-native-facebook-account-kit:preDebugBuild UP-TO-DATE
:react-native-facebook-account-kit:preDebugUnitTestBuild UP-TO-DATE
:react-native-facebook-account-kit:preReleaseUnitTestBuild UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportAnimatedVectorDrawable2531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportAppcompatV72531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportDesign2531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportRecyclerviewV72531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportSupportCompat2531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportSupportCoreUi2531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportSupportCoreUtils2531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportSupportFragment2531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportSupportMediaCompat2531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportSupportV42531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportSupportVectorDrawable2531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportTransition2531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComFacebookAndroidAccountKitSdk4240Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComFacebookFrescoDrawee101Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComFacebookFrescoFbcore101Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComFacebookFrescoFresco101Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComFacebookFrescoImagepipeline101Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComFacebookFrescoImagepipelineBase101Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComFacebookFrescoImagepipelineOkhttp3101Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComFacebookReactReactNative0460Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:react-native-facebook-account-kit:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-facebook-account-kit:prepareReleaseDependencies
:react-native-facebook-account-kit:compileReleaseAidl UP-TO-DATE
:react-native-facebook-account-kit:compileReleaseNdk UP-TO-DATE
:react-native-facebook-account-kit:compileLint UP-TO-DATE
:react-native-facebook-account-kit:copyReleaseLint UP-TO-DATE
:react-native-facebook-account-kit:compileReleaseRenderscript UP-TO-DATE
:react-native-facebook-account-kit:generateReleaseBuildConfig UP-TO-DATE
:react-native-facebook-account-kit:generateReleaseResValues UP-TO-DATE
:react-native-facebook-account-kit:generateReleaseResources UP-TO-DATE
:react-native-facebook-account-kit:mergeReleaseResources UP-TO-DATE
:react-native-facebook-account-kit:processReleaseManifest UP-TO-DATE
react-native-facebook-account-kit:processReleaseResources
/home/ReactProjects/AccountkitSample/node_modules/react-native-facebook-account-kit/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:3: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
    
/home/ReactProjects/AccountkitSample/node_modules/react-native-facebook-account-kit/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
    
/home/ReactProjects/AccountkitSample/node_modules/react-native-facebook-account-kit/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

/home/ReactProjects/AccountkitSample/node_modules/react-native-facebook-account-kit/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

:react-native-facebook-account-kit:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-facebook-account-kit:processReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

This error is coming while integrating facebook account kit to my project. I am using react-native @0.46 and account-kit @0.6.2 (latest)

**Comment by anbu369** [comment]
open build.gradle file from node_modules/react-native-facebook-account-kit/android

change 

`compile ('com.facebook.android:account-kit-sdk:4.+')`

to

`compile ('com.facebook.android:account-kit-sdk:4.23.0')`

**Comment by MuruganSKutty** [comment]
Thanks, It is working fine @anbu369
