### ISSUE TITLE
Compile error with latest react version

### ISSUE THREAD

**Issue by anbu369** [underscopeio/react-native-facebook-account-kit#81]
### Issue Description

I get the following error when I build the apk. 

```
* What went wrong:
Execution failed for task ':react-native-facebook-account-kit:prepareComFacebookAndroidAccountKitSdk4230Library'.
> Could not expand ZIP '/home/anbu/.gradle/caches/modules-2/files-2.1/com.facebook.android/account-kit-sdk/4.23.0/d175713ba1acfc061ae1709c69030703e206bf7e/account-kit-sdk-4.23.0.aar'.
```

### Steps to Reproduce / Code Snippets

I canged the build.gradle file to use facebook-account-kit-sdk-4.23.0. App runs perfectly when running from package server but could not build the release variant

#### Expected Results

bundle into apk file

### Additional Information

* React Native Account Kit version: 0.6.2
* React Native version: 0.46.1
* Platform(s) (iOS, Android, or both?): Android

**Comment by gaguirre** [comment]
Why do you need to change the `build.gradle` file?
Does it work without changing it? @anbu369

**Comment by aschenkel** [comment]
Closing it due to inactivity
