### ISSUE TITLE
Bug: Compilation with RN 0.47 on Android fails

### ISSUE THREAD

**Issue by mkozhukharenko** [underscopeio/react-native-facebook-account-kit#88]
There is a a breaking change made in react native 0.47 "Remove unused createJSModules calls"

Does anybody know how to fix this? Can we just remove '@ Override'  from this [line](https://github.com/underscopeio/react-native-facebook-account-kit/blob/master/android/src/main/java/io/underscope/react/fbak/RNAccountKitPackage.java#L16)

### Steps to Reproduce / Code Snippets

Install react Native Account Kit version: 0.7.0 and RN 0.47.1 and run `react-native run-android`

and you will get 

```
/.../node_modules/react-native-facebook-account-kit/android/src/main/java/io/underscope/react/fbak/RNAccountKitPackage.java:16: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: /../node_modules/react-native-facebook-account-kit/android/src/main/java/io/underscope/react/fbak/RNAccountKitModule.java uses or overrides a deprecated API.
```

#### Expected Results

Compilation with RN 0.47 on Android should not fail

### Additional Information

* React Native Account Kit version: 0.7.0
* React Native version: 0.47.1
* Platform: Android

**Comment by gaguirre** [comment]
Thanks for reporting this @mkozhukharenko and for the PR.
This is fixed in version **0.8.0**
