### ISSUE TITLE
White/blacklisting doesnt work?

### ISSUE THREAD

**Issue by Nopik** [underscopeio/react-native-facebook-account-kit#9]
It seems that whitelist/blacklist support doesnt really work. When I add some whitelist, still all countries are displayed. The source code doesnt seem to set `whitelistedCountryCodes` anywhere, either.

**Comment by gaguirre** [comment]
Hi @Nopik,
I'm currently working on this and hopefully will publish a new version today!

**Comment by Nopik** [comment]
Nice, thanks!
