### ISSUE TITLE
Compile error #import <React/RCTBridgeModule.h>

### ISSUE THREAD

**Issue by benclanet** [underscopeio/react-native-facebook-account-kit#94]
### Issue Description

Hey there, 
I use CRNA and just detached the app. Everything worked and built fine until I added  react-native-facebook-account-kit.
I followed all the instructions and cannot compile my project anymore.

There error says: `React/RCTBridgeModule.h file not found` in `RNAccountKit.h`

I tried to clean and re-build. 
I removed pods folder and ran `pod install`.

Do you guys have any ideas what's wrong?

Thanks!

#### Expected Results

Should compile. 👍 

### Additional Information

* React Native Account Kit version: 0.8.0
* React Native version: Expo 20.0.0
* Platform(s) (iOS, Android, or both?): iOS

**Comment by aschenkel** [comment]
Hey @benclanet ! 
Cocoapods wasn't supported until now (_v0.10.0_).
Previously only `react-native link` was supported.

**Comment by Im-Goutham** [comment]
Same issue occuring with  React Native Account Kit version: "^0.10.1"

**Comment by lucamir** [comment]
Try to remove the node_modules folder and ran npm install.
Worked on my case.
