### ISSUE TITLE
USING RNAccountKit.configure

### ISSUE THREAD

**Issue by sonydaman** [underscopeio/react-native-facebook-account-kit#95]
#Uncought Error: Undefined is not an object(evaluating 'RNAccountKit.configure')

========
CODE
========
import React from 'react';
import { StyleSheet, Text, View ,Alert,Button} from 'react-native';
import RNAccountKit from 'react-native-facebook-account-kit';

export default class App extends React.Component {
  constructor(props) {
    super(props);
    this.state = { login: false } ;
     RNAccountKit.configure({
        responseType: 'token',
        titleType: 'login',
        initialAuthState: '',
        initialEmail: 'test@email.com',
        initialPhoneCountryPrefix: '+91,
        initialPhoneNumber: '8950859785',
        facebookNotificationsEnabled: true, // true by default
        readPhoneStateEnabled: true, // true by default,
        receiveSMS: true, // true by default,
        countryWhitelist: ['AR'], // [] by default
        countryBlacklist: ['US'], // [] by default
        defaultCountry: 'IN',
        theme: {} 
      })
  }

  componentWillMount() {
  }
  login(){
    Alert.alert("Hi","THIS IS TITLE");
  }
  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
        <Button
          title="Press me"
          onPress={this.login}
        />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
==================
ERROR  Screenshot
=====================
(https://user-images.githubusercontent.com/7029004/30006107-60becaa6-910e-11e7-9832-b4a63159fe1e.jpeg)
'

https://user-images.githubusercontent.com/7029004/30006081-fd3c35d6-910d-11e7-933b-a6082ac462bb.jpeg

**Comment by gaguirre** [comment]
This happens when the module is not properly configured.
Please follow the [configuration steps](https://github.com/underscopeio/react-native-facebook-account-kit#configuration) carefully 👍
