### ISSUE TITLE
Build Error: "RNAccountKitPackage is not abstract and does not override abstract method createJSModules() in ReactPackage"

### ISSUE THREAD

**Issue by mypark** [underscopeio/react-native-facebook-account-kit#96]
### Issue Description

I'm getting a compile error when trying to build the android version 

[ERROR] [system.err] /Users/foo/Projects/my-app/node_modules/react-native-facebook-account-kit/android/src/main/java/io/underscope/react/fbak/RNAccountKitPackage.java:14: error: RNAccountKitPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
16:49:44.347 [ERROR] [system.err] public class RNAccountKitPackage implements ReactPackage {
16:49:44.347 [ERROR] [system.err]        ^
16:49:44.431 [ERROR] [system.err] Note: /Users/foo/Projects/my-app/node_modules/react-native-facebook-account-kit/android/src/main/java/io/underscope/react/fbak/RNAccountKitModule.java uses or overrides a deprecated API.
16:49:44.431 [ERROR] [system.err] Note: Recompile with -Xlint:deprecation for details.
16:49:44.432 [ERROR] [system.err] 1 error

### Steps to Reproduce / Code Snippets

react-native run-android

OR

./gradlew assembleRelease

#### Expected Results

Expected no error on build

### Additional Information

* React Native Account Kit version: 0.8
* React Native version: 0.41.2
* Platform: Android

**Comment by gaguirre** [comment]
This was fixed in already realeased version `0.8.0`

**Comment by zachrnolan** [comment]
I'm still running into this error on RN 0.48 & 0.9.0.

**Comment by pewh** [comment]
Still have same issue on RN 0.50.4

**Comment by Deevent** [comment]
Same issue, anyone has the solution ?

**Comment by dattran97** [comment]
Same issue on "react-native": "0.57.7" and "react-native-facebook-account-kit": "1.0.1"

**Comment by jpgarcia** [comment]
Hi @dattran97 I've just put together a new example [RN0577](https://github.com/underscopeio/react-native-facebook-account-kit/tree/master/examples/RN0577) with the versions you mention and it works. You can compare it with your code to see what can be wrong.
