### ISSUE TITLE
NPM INSTALL NOT WORKING

### ISSUE THREAD

**Issue by sonydaman** [underscopeio/react-native-facebook-account-kit#97]
F:\xampp_New\htdocs\REPO\REACTNATIVE\react-native-facebook-account-kit\examples\RN024>npm install

> bufferutil@1.2.1 install F:\xampp_New\htdocs\REPO\REACTNATIVE\react-native-facebook-account-kit\examples\RN024\node_mo
dules\bufferutil
> node-gyp rebuild

F:\xampp_New\htdocs\REPO\REACTNATIVE\react-native-facebook-account-kit\examples\RN024\node_modules\bufferutil>if not def
ined npm_config_node_gyp (node "C:\Users\SonyDaman\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_mod
ules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
F:\xampp_New\htdocs\REPO\REACTNATIVE\react-native-facebook-account-kit\examples\RN024\node_modules\bufferutil\build\buf
ferutil.vcxproj(20,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Micr
osoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file
 exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\SonyDaman\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp
\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\SonyDaman\\AppData\\Roaming\\npm\\node_modules\\npm\\
node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\xampp_New\htdocs\REPO\REACTNATIVE\react-native-facebook-account-kit\examples\RN024\node_modules\bufferut
il
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules\bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 115 packages in 67.918s

========================================
After trying node-gyp rebuild : 
=============================================
F:\xampp_New\htdocs\REPO\REACTNATIVE\react-native-facebook-account-kit\examples\RN024>npm install node-gyp rebuild

> bufferutil@1.2.1 install F:\xampp_New\htdocs\REPO\REACTNATIVE\react-native-facebook-account-kit\examples\RN024\node_mo
dules\bufferutil
> node-gyp rebuild

F:\xampp_New\htdocs\REPO\REACTNATIVE\react-native-facebook-account-kit\examples\RN024\node_modules\bufferutil>if not def
ined npm_config_node_gyp (node "C:\Users\SonyDaman\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_mod
ules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
F:\xampp_New\htdocs\REPO\REACTNATIVE\react-native-facebook-account-kit\examples\RN024\node_modules\bufferutil\build\buf
ferutil.vcxproj(20,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Micr
osoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file
 exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\SonyDaman\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp
\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\SonyDaman\\AppData\\Roaming\\npm\\node_modules\\npm\\
node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\xampp_New\htdocs\REPO\REACTNATIVE\react-native-facebook-account-kit\examples\RN024\node_modules\bufferut
il
gyp ERR! node -v v6.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 (node_modules\bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ node-gyp@3.6.2
+ rebuild@0.1.2
added 172 packages in 56.633s

**Comment by gaguirre** [comment]
Could you try with one of a newer example (`RN040` or `RN048`)?
Version 24 of React Native is not supported anymore in this module.
