### ISSUE TITLE
ERROR IN eact-native-facebook-account-kit:processReleaseResources

### ISSUE THREAD

**Issue by sonydaman** [underscopeio/react-native-facebook-account-kit#98]
F:\xampp_New\htdocs\REPO\REACTNATIVE\react-native-facebook-account-kit\examples\RN024>react-native run-android
(node:7232) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
Starting JS server...
Starting the packager in a new window is not supported on Windows yet.
Please start it manually using 'react-native start'.
We believe the best Windows support will come from a community of people
using React Native on Windows on a daily basis.
Would you be up for sending a pull request?
Building and installing the app on the device (cd android && gradlew.bat installDebug...
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:react-native-facebook-account-kit:compileLint
:react-native-facebook-account-kit:copyReleaseLint UP-TO-DATE
:react-native-facebook-account-kit:preBuild UP-TO-DATE
:react-native-facebook-account-kit:preReleaseBuild UP-TO-DATE
:react-native-facebook-account-kit:checkReleaseManifest
:react-native-facebook-account-kit:preDebugAndroidTestBuild UP-TO-DATE
:react-native-facebook-account-kit:preDebugBuild UP-TO-DATE
:react-native-facebook-account-kit:preDebugUnitTestBuild UP-TO-DATE
:react-native-facebook-account-kit:preReleaseUnitTestBuild UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportAnimatedVectorDrawable2531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportAppcompatV72531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportDesign2531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportRecyclerviewV72531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportSupportCompat2531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportSupportCoreUi2531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportSupportCoreUtils2531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportSupportFragment2531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportSupportMediaCompat2531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportSupportV42531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportSupportVectorDrawable2531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComAndroidSupportTransition2531Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComFacebookAndroidAccountKitSdk4260Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComFacebookFrescoDrawee081Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComFacebookFrescoFbcore081Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComFacebookFrescoFresco081Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComFacebookFrescoImagepipeline081Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComFacebookFrescoImagepipelineOkhttp081Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComFacebookReactReactNative0201Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComGoogleAndroidGmsPlayServicesAuth1101Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComGoogleAndroidGmsPlayServicesAuthApiPhone1101Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComGoogleAndroidGmsPlayServicesAuthBase1101Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComGoogleAndroidGmsPlayServicesBase1101Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComGoogleAndroidGmsPlayServicesBasement1101Library UP-TO-DATE
:react-native-facebook-account-kit:prepareComGoogleAndroidGmsPlayServicesTasks1101Library UP-TO-DATE
:react-native-facebook-account-kit:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-facebook-account-kit:prepareReleaseDependencies
:react-native-facebook-account-kit:compileReleaseAidl UP-TO-DATE
:react-native-facebook-account-kit:compileReleaseRenderscript UP-TO-DATE
:react-native-facebook-account-kit:generateReleaseBuildConfig UP-TO-DATE
:react-native-facebook-account-kit:generateReleaseAssets UP-TO-DATE
:react-native-facebook-account-kit:mergeReleaseAssets UP-TO-DATE
:react-native-facebook-account-kit:generateReleaseResValues UP-TO-DATE
:react-native-facebook-account-kit:generateReleaseResources UP-TO-DATE
:react-native-facebook-account-kit:mergeReleaseResources UP-TO-DATE
:react-native-facebook-account-kit:processReleaseManifest UP-TO-DATE
:react-native-facebook-account-kit:processReleaseResources
F:\xampp_New\htdocs\REPO\REACTNATIVE\react-native-facebook-account-kit\examples\RN024\node_modules\react-native-facebook-account-kit\an
droid\build\intermediates\exploded-aar\com.android.support\appcompat-v7\25.3.1\res\values-v24\values-v24.xml:2 : Error retrieving paren
t for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
F:\xampp_New\htdocs\REPO\REACTNATIVE\react-native-facebook-account-kit\examples\RN024\node_modules\react-native-facebook-account-kit\an
droid\build\intermediates\exploded-aar\com.android.support\appcompat-v7\25.3.1\res\values-v24\values-v24.xml:2 : Error retrieving paren
t for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

:react-native-facebook-account-kit:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-facebook-account-kit:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'F:\Software\Android\OLD
\adt-bundle-windows-x86_64-20140702\sdk\build-tools\23.0.2\aapt.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 39.428 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by gaguirre** [comment]
Will close this for the same reason than #97
